#pragma once

struct PokedexEntry
{
    /*0x00*/ u8 categoryName[12];
    /*0x0C*/ u16 height; //in decimeters
    /*0x0E*/ u16 weight; //in hectograms
    /*0x10*/ const u8* description;
    /*0x14*/ const u8* unusedDescription;
    /*0x18*/ u16 unused;
    /*0x1A*/ u16 pokemonScale;
    /*0x1C*/ u16 pokemonOffset;
    /*0x1E*/ u16 trainerScale;
    /*0x20*/ u16 trainerOffset;
	/*0x22*/ u16 unused2;
};  /*size = 0x24*/

struct AlternateDexEntries
{
	u16 species;
	const u8* description;
};

struct ListMenuItem
{
    const u8* name;
    s32 id;
};

struct PokedexScreenData
{
    u8 field_00;
    u8 field_01;
    u8 field_02;
    u8 field_03;
    u8 field_04;
    u32 field_08;
    u32 field_0C;
    u16 field_10;
    u16 field_12;
    u8 field_14;
    u8 field_15;
    u8 field_16;
    u8 field_17;
    u16 field_18[0x4];
    u8 field_20[0x4];
    u8 field_24[0x4];
    u8 field_28;
    u8 field_29;
    u8 field_2A;
    u8 field_2B;
    u8 field_2C;
    u8 field_2D;
    u8 field_2E;
    u8 field_2F;
    u32 field_30;
    u16 field_34;
    u16 field_36;
    u16 field_38;
    u16 field_3A;
    u16 field_3C;
    u16 field_3E;
    u8 field_40;
    u8 field_41;
    u8 field_42;
    struct ListMenuItem* listItem;
    u16 field_48;
    u8 field_4A[0x10];
    u16 field_5A;
    u16 * field_5C;
    u8 field_60;
    u8 field_61;
    u16 field_62;
    u8 field_64;
    u16 field_66;
    u16 field_68;
    u16 field_6A;
    u16 field_6C;
};

extern struct PokedexScreenData* gPokedexScreenDataPtr;

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

//Gartic
#define NATIONAL_DEX_NONE 0
#define NATIONAL_DEX_BULLFROCK 1
#define FINAL_GARTIC_ENTRY NATIONAL_DEX_BULLFROCK

//Kanto
#define NATIONAL_DEX_BULBASAUR FINAL_GARTIC_ENTRY + 1
#define NATIONAL_DEX_IVYSAUR FINAL_GARTIC_ENTRY + 2
#define NATIONAL_DEX_VENUSAUR FINAL_GARTIC_ENTRY + 3
#define NATIONAL_DEX_CHARMANDER FINAL_GARTIC_ENTRY + 4
#define NATIONAL_DEX_CHARMELEON FINAL_GARTIC_ENTRY + 5
#define NATIONAL_DEX_CHARIZARD FINAL_GARTIC_ENTRY + 6
#define NATIONAL_DEX_SQUIRTLE FINAL_GARTIC_ENTRY + 7
#define NATIONAL_DEX_WARTORTLE FINAL_GARTIC_ENTRY + 8
#define NATIONAL_DEX_BLASTOISE FINAL_GARTIC_ENTRY + 9
#define NATIONAL_DEX_CATERPIE FINAL_GARTIC_ENTRY + 10
#define NATIONAL_DEX_METAPOD FINAL_GARTIC_ENTRY + 11
#define NATIONAL_DEX_BUTTERFREE FINAL_GARTIC_ENTRY + 12
#define NATIONAL_DEX_WEEDLE FINAL_GARTIC_ENTRY + 13
#define NATIONAL_DEX_KAKUNA FINAL_GARTIC_ENTRY + 14
#define NATIONAL_DEX_BEEDRILL FINAL_GARTIC_ENTRY + 15
#define NATIONAL_DEX_PIDGEY FINAL_GARTIC_ENTRY + 16
#define NATIONAL_DEX_PIDGEOTTO FINAL_GARTIC_ENTRY + 17
#define NATIONAL_DEX_PIDGEOT FINAL_GARTIC_ENTRY + 18
#define NATIONAL_DEX_RATTATA FINAL_GARTIC_ENTRY + 19
#define NATIONAL_DEX_RATICATE FINAL_GARTIC_ENTRY + 20
#define NATIONAL_DEX_SPEAROW FINAL_GARTIC_ENTRY + 21
#define NATIONAL_DEX_FEAROW FINAL_GARTIC_ENTRY + 22
#define NATIONAL_DEX_EKANS FINAL_GARTIC_ENTRY + 23
#define NATIONAL_DEX_ARBOK FINAL_GARTIC_ENTRY + 24
#define NATIONAL_DEX_PIKACHU FINAL_GARTIC_ENTRY + 25
#define NATIONAL_DEX_RAICHU FINAL_GARTIC_ENTRY + 26
#define NATIONAL_DEX_SANDSHREW FINAL_GARTIC_ENTRY + 27
#define NATIONAL_DEX_SANDSLASH FINAL_GARTIC_ENTRY + 28
#define NATIONAL_DEX_NIDORAN_F FINAL_GARTIC_ENTRY + 29
#define NATIONAL_DEX_NIDORINA FINAL_GARTIC_ENTRY + 30
#define NATIONAL_DEX_NIDOQUEEN FINAL_GARTIC_ENTRY + 31
#define NATIONAL_DEX_NIDORAN_M FINAL_GARTIC_ENTRY + 32
#define NATIONAL_DEX_NIDORINO FINAL_GARTIC_ENTRY + 33
#define NATIONAL_DEX_NIDOKING FINAL_GARTIC_ENTRY + 34
#define NATIONAL_DEX_CLEFAIRY FINAL_GARTIC_ENTRY + 35
#define NATIONAL_DEX_CLEFABLE FINAL_GARTIC_ENTRY + 36
#define NATIONAL_DEX_VULPIX FINAL_GARTIC_ENTRY + 37
#define NATIONAL_DEX_NINETALES FINAL_GARTIC_ENTRY + 38
#define NATIONAL_DEX_JIGGLYPUFF FINAL_GARTIC_ENTRY + 39
#define NATIONAL_DEX_WIGGLYTUFF FINAL_GARTIC_ENTRY + 40
#define NATIONAL_DEX_ZUBAT FINAL_GARTIC_ENTRY + 41
#define NATIONAL_DEX_GOLBAT FINAL_GARTIC_ENTRY + 42
#define NATIONAL_DEX_ODDISH FINAL_GARTIC_ENTRY + 43
#define NATIONAL_DEX_GLOOM FINAL_GARTIC_ENTRY + 44
#define NATIONAL_DEX_VILEPLUME FINAL_GARTIC_ENTRY + 45
#define NATIONAL_DEX_PARAS FINAL_GARTIC_ENTRY + 46
#define NATIONAL_DEX_PARASECT FINAL_GARTIC_ENTRY + 47
#define NATIONAL_DEX_VENONAT FINAL_GARTIC_ENTRY + 48
#define NATIONAL_DEX_VENOMOTH FINAL_GARTIC_ENTRY + 49
#define NATIONAL_DEX_DIGLETT FINAL_GARTIC_ENTRY + 50
#define NATIONAL_DEX_DUGTRIO FINAL_GARTIC_ENTRY + 51
#define NATIONAL_DEX_MEOWTH FINAL_GARTIC_ENTRY + 52
#define NATIONAL_DEX_PERSIAN FINAL_GARTIC_ENTRY + 53
#define NATIONAL_DEX_PSYDUCK FINAL_GARTIC_ENTRY + 54
#define NATIONAL_DEX_GOLDUCK FINAL_GARTIC_ENTRY + 55
#define NATIONAL_DEX_MANKEY FINAL_GARTIC_ENTRY + 56
#define NATIONAL_DEX_PRIMEAPE FINAL_GARTIC_ENTRY + 57
#define NATIONAL_DEX_GROWLITHE FINAL_GARTIC_ENTRY + 58
#define NATIONAL_DEX_ARCANINE FINAL_GARTIC_ENTRY + 59
#define NATIONAL_DEX_POLIWAG FINAL_GARTIC_ENTRY + 60
#define NATIONAL_DEX_POLIWHIRL FINAL_GARTIC_ENTRY + 61
#define NATIONAL_DEX_POLIWRATH FINAL_GARTIC_ENTRY + 62
#define NATIONAL_DEX_ABRA FINAL_GARTIC_ENTRY + 63
#define NATIONAL_DEX_KADABRA FINAL_GARTIC_ENTRY + 64
#define NATIONAL_DEX_ALAKAZAM FINAL_GARTIC_ENTRY + 65
#define NATIONAL_DEX_MACHOP FINAL_GARTIC_ENTRY + 66
#define NATIONAL_DEX_MACHOKE FINAL_GARTIC_ENTRY + 67
#define NATIONAL_DEX_MACHAMP FINAL_GARTIC_ENTRY + 68
#define NATIONAL_DEX_BELLSPROUT FINAL_GARTIC_ENTRY + 69
#define NATIONAL_DEX_WEEPINBELL FINAL_GARTIC_ENTRY + 70
#define NATIONAL_DEX_VICTREEBEL FINAL_GARTIC_ENTRY + 71
#define NATIONAL_DEX_TENTACOOL FINAL_GARTIC_ENTRY + 72
#define NATIONAL_DEX_TENTACRUEL FINAL_GARTIC_ENTRY + 73
#define NATIONAL_DEX_GEODUDE FINAL_GARTIC_ENTRY + 74
#define NATIONAL_DEX_GRAVELER FINAL_GARTIC_ENTRY + 75
#define NATIONAL_DEX_GOLEM FINAL_GARTIC_ENTRY + 76
#define NATIONAL_DEX_PONYTA FINAL_GARTIC_ENTRY + 77
#define NATIONAL_DEX_RAPIDASH FINAL_GARTIC_ENTRY + 78
#define NATIONAL_DEX_SLOWPOKE FINAL_GARTIC_ENTRY + 79
#define NATIONAL_DEX_SLOWBRO FINAL_GARTIC_ENTRY + 80
#define NATIONAL_DEX_MAGNEMITE FINAL_GARTIC_ENTRY + 81
#define NATIONAL_DEX_MAGNETON FINAL_GARTIC_ENTRY + 82
#define NATIONAL_DEX_FARFETCHD FINAL_GARTIC_ENTRY + 83
#define NATIONAL_DEX_DODUO FINAL_GARTIC_ENTRY + 84
#define NATIONAL_DEX_DODRIO FINAL_GARTIC_ENTRY + 85
#define NATIONAL_DEX_SEEL FINAL_GARTIC_ENTRY + 86
#define NATIONAL_DEX_DEWGONG FINAL_GARTIC_ENTRY + 87
#define NATIONAL_DEX_GRIMER FINAL_GARTIC_ENTRY + 88
#define NATIONAL_DEX_MUK FINAL_GARTIC_ENTRY + 89
#define NATIONAL_DEX_SHELLDER FINAL_GARTIC_ENTRY + 90
#define NATIONAL_DEX_CLOYSTER FINAL_GARTIC_ENTRY + 91
#define NATIONAL_DEX_GASTLY FINAL_GARTIC_ENTRY + 92
#define NATIONAL_DEX_HAUNTER FINAL_GARTIC_ENTRY + 93
#define NATIONAL_DEX_GENGAR FINAL_GARTIC_ENTRY + 94
#define NATIONAL_DEX_ONIX FINAL_GARTIC_ENTRY + 95
#define NATIONAL_DEX_DROWZEE FINAL_GARTIC_ENTRY + 96
#define NATIONAL_DEX_HYPNO FINAL_GARTIC_ENTRY + 97
#define NATIONAL_DEX_KRABBY FINAL_GARTIC_ENTRY + 98
#define NATIONAL_DEX_KINGLER FINAL_GARTIC_ENTRY + 99
#define NATIONAL_DEX_VOLTORB FINAL_GARTIC_ENTRY + 100
#define NATIONAL_DEX_ELECTRODE FINAL_GARTIC_ENTRY + 101
#define NATIONAL_DEX_EXEGGCUTE FINAL_GARTIC_ENTRY + 102
#define NATIONAL_DEX_EXEGGUTOR FINAL_GARTIC_ENTRY + 103
#define NATIONAL_DEX_CUBONE FINAL_GARTIC_ENTRY + 104
#define NATIONAL_DEX_MAROWAK FINAL_GARTIC_ENTRY + 105
#define NATIONAL_DEX_HITMONLEE FINAL_GARTIC_ENTRY + 106
#define NATIONAL_DEX_HITMONCHAN FINAL_GARTIC_ENTRY + 107
#define NATIONAL_DEX_LICKITUNG FINAL_GARTIC_ENTRY + 108
#define NATIONAL_DEX_KOFFING FINAL_GARTIC_ENTRY + 109
#define NATIONAL_DEX_WEEZING FINAL_GARTIC_ENTRY + 110
#define NATIONAL_DEX_RHYHORN FINAL_GARTIC_ENTRY + 111
#define NATIONAL_DEX_RHYDON FINAL_GARTIC_ENTRY + 112
#define NATIONAL_DEX_CHANSEY FINAL_GARTIC_ENTRY + 113
#define NATIONAL_DEX_TANGELA FINAL_GARTIC_ENTRY + 114
#define NATIONAL_DEX_KANGASKHAN FINAL_GARTIC_ENTRY + 115
#define NATIONAL_DEX_HORSEA FINAL_GARTIC_ENTRY + 116
#define NATIONAL_DEX_SEADRA FINAL_GARTIC_ENTRY + 117
#define NATIONAL_DEX_GOLDEEN FINAL_GARTIC_ENTRY + 118
#define NATIONAL_DEX_SEAKING FINAL_GARTIC_ENTRY + 119
#define NATIONAL_DEX_STARYU FINAL_GARTIC_ENTRY + 120
#define NATIONAL_DEX_STARMIE FINAL_GARTIC_ENTRY + 121
#define NATIONAL_DEX_MR_MIME FINAL_GARTIC_ENTRY + 122
#define NATIONAL_DEX_SCYTHER FINAL_GARTIC_ENTRY + 123
#define NATIONAL_DEX_JYNX FINAL_GARTIC_ENTRY + 124
#define NATIONAL_DEX_ELECTABUZZ FINAL_GARTIC_ENTRY + 125
#define NATIONAL_DEX_MAGMAR FINAL_GARTIC_ENTRY + 126
#define NATIONAL_DEX_PINSIR FINAL_GARTIC_ENTRY + 127
#define NATIONAL_DEX_TAUROS FINAL_GARTIC_ENTRY + 128
#define NATIONAL_DEX_MAGIKARP FINAL_GARTIC_ENTRY + 129
#define NATIONAL_DEX_GYARADOS FINAL_GARTIC_ENTRY + 130
#define NATIONAL_DEX_LAPRAS FINAL_GARTIC_ENTRY + 131
#define NATIONAL_DEX_DITTO FINAL_GARTIC_ENTRY + 132
#define NATIONAL_DEX_EEVEE FINAL_GARTIC_ENTRY + 133
#define NATIONAL_DEX_VAPOREON FINAL_GARTIC_ENTRY + 134
#define NATIONAL_DEX_JOLTEON FINAL_GARTIC_ENTRY + 135
#define NATIONAL_DEX_FLAREON FINAL_GARTIC_ENTRY + 136
#define NATIONAL_DEX_PORYGON FINAL_GARTIC_ENTRY + 137
#define NATIONAL_DEX_OMANYTE FINAL_GARTIC_ENTRY + 138
#define NATIONAL_DEX_OMASTAR FINAL_GARTIC_ENTRY + 139
#define NATIONAL_DEX_KABUTO FINAL_GARTIC_ENTRY + 140
#define NATIONAL_DEX_KABUTOPS FINAL_GARTIC_ENTRY + 141
#define NATIONAL_DEX_AERODACTYL FINAL_GARTIC_ENTRY + 142
#define NATIONAL_DEX_SNORLAX FINAL_GARTIC_ENTRY + 143
#define NATIONAL_DEX_ARTICUNO FINAL_GARTIC_ENTRY + 144
#define NATIONAL_DEX_ZAPDOS FINAL_GARTIC_ENTRY + 145
#define NATIONAL_DEX_MOLTRES FINAL_GARTIC_ENTRY + 146
#define NATIONAL_DEX_DRATINI FINAL_GARTIC_ENTRY + 147
#define NATIONAL_DEX_DRAGONAIR FINAL_GARTIC_ENTRY + 148
#define NATIONAL_DEX_DRAGONITE FINAL_GARTIC_ENTRY + 149
#define NATIONAL_DEX_MEWTWO FINAL_GARTIC_ENTRY + 150
#define NATIONAL_DEX_MEW FINAL_GARTIC_ENTRY + 151

//Johto
#define NATIONAL_DEX_CHIKORITA FINAL_GARTIC_ENTRY + 152
#define NATIONAL_DEX_BAYLEEF FINAL_GARTIC_ENTRY + 153
#define NATIONAL_DEX_MEGANIUM FINAL_GARTIC_ENTRY + 154
#define NATIONAL_DEX_CYNDAQUIL FINAL_GARTIC_ENTRY + 155
#define NATIONAL_DEX_QUILAVA FINAL_GARTIC_ENTRY + 156
#define NATIONAL_DEX_TYPHLOSION FINAL_GARTIC_ENTRY + 157
#define NATIONAL_DEX_TOTODILE FINAL_GARTIC_ENTRY + 158
#define NATIONAL_DEX_CROCONAW FINAL_GARTIC_ENTRY + 159
#define NATIONAL_DEX_FERALIGATR FINAL_GARTIC_ENTRY + 160
#define NATIONAL_DEX_SENTRET FINAL_GARTIC_ENTRY + 161
#define NATIONAL_DEX_FURRET FINAL_GARTIC_ENTRY + 162
#define NATIONAL_DEX_HOOTHOOT FINAL_GARTIC_ENTRY + 163
#define NATIONAL_DEX_NOCTOWL FINAL_GARTIC_ENTRY + 164
#define NATIONAL_DEX_LEDYBA FINAL_GARTIC_ENTRY + 165
#define NATIONAL_DEX_LEDIAN FINAL_GARTIC_ENTRY + 166
#define NATIONAL_DEX_SPINARAK FINAL_GARTIC_ENTRY + 167
#define NATIONAL_DEX_ARIADOS FINAL_GARTIC_ENTRY + 168
#define NATIONAL_DEX_CROBAT FINAL_GARTIC_ENTRY + 169
#define NATIONAL_DEX_CHINCHOU FINAL_GARTIC_ENTRY + 170
#define NATIONAL_DEX_LANTURN FINAL_GARTIC_ENTRY + 171
#define NATIONAL_DEX_PICHU FINAL_GARTIC_ENTRY + 172
#define NATIONAL_DEX_CLEFFA FINAL_GARTIC_ENTRY + 173
#define NATIONAL_DEX_IGGLYBUFF FINAL_GARTIC_ENTRY + 174
#define NATIONAL_DEX_TOGEPI FINAL_GARTIC_ENTRY + 175
#define NATIONAL_DEX_TOGETIC FINAL_GARTIC_ENTRY + 176
#define NATIONAL_DEX_NATU FINAL_GARTIC_ENTRY + 177
#define NATIONAL_DEX_XATU FINAL_GARTIC_ENTRY + 178
#define NATIONAL_DEX_MAREEP FINAL_GARTIC_ENTRY + 179
#define NATIONAL_DEX_FLAAFFY FINAL_GARTIC_ENTRY + 180
#define NATIONAL_DEX_AMPHAROS FINAL_GARTIC_ENTRY + 181
#define NATIONAL_DEX_BELLOSSOM FINAL_GARTIC_ENTRY + 182
#define NATIONAL_DEX_MARILL FINAL_GARTIC_ENTRY + 183
#define NATIONAL_DEX_AZUMARILL FINAL_GARTIC_ENTRY + 184
#define NATIONAL_DEX_SUDOWOODO FINAL_GARTIC_ENTRY + 185
#define NATIONAL_DEX_POLITOED FINAL_GARTIC_ENTRY + 186
#define NATIONAL_DEX_HOPPIP FINAL_GARTIC_ENTRY + 187
#define NATIONAL_DEX_SKIPLOOM FINAL_GARTIC_ENTRY + 188
#define NATIONAL_DEX_JUMPLUFF FINAL_GARTIC_ENTRY + 189
#define NATIONAL_DEX_AIPOM FINAL_GARTIC_ENTRY + 190
#define NATIONAL_DEX_SUNKERN FINAL_GARTIC_ENTRY + 191
#define NATIONAL_DEX_SUNFLORA FINAL_GARTIC_ENTRY + 192
#define NATIONAL_DEX_YANMA FINAL_GARTIC_ENTRY + 193
#define NATIONAL_DEX_WOOPER FINAL_GARTIC_ENTRY + 194
#define NATIONAL_DEX_QUAGSIRE FINAL_GARTIC_ENTRY + 195
#define NATIONAL_DEX_ESPEON FINAL_GARTIC_ENTRY + 196
#define NATIONAL_DEX_UMBREON FINAL_GARTIC_ENTRY + 197
#define NATIONAL_DEX_MURKROW FINAL_GARTIC_ENTRY + 198
#define NATIONAL_DEX_SLOWKING FINAL_GARTIC_ENTRY + 199
#define NATIONAL_DEX_MISDREAVUS FINAL_GARTIC_ENTRY + 200
#define NATIONAL_DEX_UNOWN FINAL_GARTIC_ENTRY + 201
#define NATIONAL_DEX_WOBBUFFET FINAL_GARTIC_ENTRY + 202
#define NATIONAL_DEX_GIRAFARIG FINAL_GARTIC_ENTRY + 203
#define NATIONAL_DEX_PINECO FINAL_GARTIC_ENTRY + 204
#define NATIONAL_DEX_FORRETRESS FINAL_GARTIC_ENTRY + 205
#define NATIONAL_DEX_DUNSPARCE FINAL_GARTIC_ENTRY + 206
#define NATIONAL_DEX_GLIGAR FINAL_GARTIC_ENTRY + 207
#define NATIONAL_DEX_STEELIX FINAL_GARTIC_ENTRY + 208
#define NATIONAL_DEX_SNUBBULL FINAL_GARTIC_ENTRY + 209
#define NATIONAL_DEX_GRANBULL FINAL_GARTIC_ENTRY + 210
#define NATIONAL_DEX_QWILFISH FINAL_GARTIC_ENTRY + 211
#define NATIONAL_DEX_SCIZOR FINAL_GARTIC_ENTRY + 212
#define NATIONAL_DEX_SHUCKLE FINAL_GARTIC_ENTRY + 213
#define NATIONAL_DEX_HERACROSS FINAL_GARTIC_ENTRY + 214
#define NATIONAL_DEX_SNEASEL FINAL_GARTIC_ENTRY + 215
#define NATIONAL_DEX_TEDDIURSA FINAL_GARTIC_ENTRY + 216
#define NATIONAL_DEX_URSARING FINAL_GARTIC_ENTRY + 217
#define NATIONAL_DEX_SLUGMA FINAL_GARTIC_ENTRY + 218
#define NATIONAL_DEX_MAGCARGO FINAL_GARTIC_ENTRY + 219
#define NATIONAL_DEX_SWINUB FINAL_GARTIC_ENTRY + 220
#define NATIONAL_DEX_PILOSWINE FINAL_GARTIC_ENTRY + 221
#define NATIONAL_DEX_CORSOLA FINAL_GARTIC_ENTRY + 222
#define NATIONAL_DEX_REMORAID FINAL_GARTIC_ENTRY + 223
#define NATIONAL_DEX_OCTILLERY FINAL_GARTIC_ENTRY + 224
#define NATIONAL_DEX_DELIBIRD FINAL_GARTIC_ENTRY + 225
#define NATIONAL_DEX_MANTINE FINAL_GARTIC_ENTRY + 226
#define NATIONAL_DEX_SKARMORY FINAL_GARTIC_ENTRY + 227
#define NATIONAL_DEX_HOUNDOUR FINAL_GARTIC_ENTRY + 228
#define NATIONAL_DEX_HOUNDOOM FINAL_GARTIC_ENTRY + 229
#define NATIONAL_DEX_KINGDRA FINAL_GARTIC_ENTRY + 230
#define NATIONAL_DEX_PHANPY FINAL_GARTIC_ENTRY + 231
#define NATIONAL_DEX_DONPHAN FINAL_GARTIC_ENTRY + 232
#define NATIONAL_DEX_PORYGON2 FINAL_GARTIC_ENTRY + 233
#define NATIONAL_DEX_STANTLER FINAL_GARTIC_ENTRY + 234
#define NATIONAL_DEX_SMEARGLE FINAL_GARTIC_ENTRY + 235
#define NATIONAL_DEX_TYROGUE FINAL_GARTIC_ENTRY + 236
#define NATIONAL_DEX_HITMONTOP FINAL_GARTIC_ENTRY + 237
#define NATIONAL_DEX_SMOOCHUM FINAL_GARTIC_ENTRY + 238
#define NATIONAL_DEX_ELEKID FINAL_GARTIC_ENTRY + 239
#define NATIONAL_DEX_MAGBY FINAL_GARTIC_ENTRY + 240
#define NATIONAL_DEX_MILTANK FINAL_GARTIC_ENTRY + 241
#define NATIONAL_DEX_BLISSEY FINAL_GARTIC_ENTRY + 242
#define NATIONAL_DEX_RAIKOU FINAL_GARTIC_ENTRY + 243
#define NATIONAL_DEX_ENTEI FINAL_GARTIC_ENTRY + 244
#define NATIONAL_DEX_SUICUNE FINAL_GARTIC_ENTRY + 245
#define NATIONAL_DEX_LARVITAR FINAL_GARTIC_ENTRY + 246
#define NATIONAL_DEX_PUPITAR FINAL_GARTIC_ENTRY + 247
#define NATIONAL_DEX_TYRANITAR FINAL_GARTIC_ENTRY + 248
#define NATIONAL_DEX_LUGIA FINAL_GARTIC_ENTRY + 249
#define NATIONAL_DEX_HO_OH FINAL_GARTIC_ENTRY + 250
#define NATIONAL_DEX_CELEBI FINAL_GARTIC_ENTRY + 251

//Hoenn
#define NATIONAL_DEX_TREECKO FINAL_GARTIC_ENTRY + 252
#define NATIONAL_DEX_GROVYLE FINAL_GARTIC_ENTRY + 253
#define NATIONAL_DEX_SCEPTILE FINAL_GARTIC_ENTRY + 254
#define NATIONAL_DEX_TORCHIC FINAL_GARTIC_ENTRY + 255
#define NATIONAL_DEX_COMBUSKEN FINAL_GARTIC_ENTRY + 256
#define NATIONAL_DEX_BLAZIKEN FINAL_GARTIC_ENTRY + 257
#define NATIONAL_DEX_MUDKIP FINAL_GARTIC_ENTRY + 258
#define NATIONAL_DEX_MARSHTOMP FINAL_GARTIC_ENTRY + 259
#define NATIONAL_DEX_SWAMPERT FINAL_GARTIC_ENTRY + 260
#define NATIONAL_DEX_POOCHYENA FINAL_GARTIC_ENTRY + 261
#define NATIONAL_DEX_MIGHTYENA FINAL_GARTIC_ENTRY + 262
#define NATIONAL_DEX_ZIGZAGOON FINAL_GARTIC_ENTRY + 263
#define NATIONAL_DEX_LINOONE FINAL_GARTIC_ENTRY + 264
#define NATIONAL_DEX_WURMPLE FINAL_GARTIC_ENTRY + 265
#define NATIONAL_DEX_SILCOON FINAL_GARTIC_ENTRY + 266
#define NATIONAL_DEX_BEAUTIFLY FINAL_GARTIC_ENTRY + 267
#define NATIONAL_DEX_CASCOON FINAL_GARTIC_ENTRY + 268
#define NATIONAL_DEX_DUSTOX FINAL_GARTIC_ENTRY + 269
#define NATIONAL_DEX_LOTAD FINAL_GARTIC_ENTRY + 270
#define NATIONAL_DEX_LOMBRE FINAL_GARTIC_ENTRY + 271
#define NATIONAL_DEX_LUDICOLO FINAL_GARTIC_ENTRY + 272
#define NATIONAL_DEX_SEEDOT FINAL_GARTIC_ENTRY + 273
#define NATIONAL_DEX_NUZLEAF FINAL_GARTIC_ENTRY + 274
#define NATIONAL_DEX_SHIFTRY FINAL_GARTIC_ENTRY + 275
#define NATIONAL_DEX_TAILLOW FINAL_GARTIC_ENTRY + 276
#define NATIONAL_DEX_SWELLOW FINAL_GARTIC_ENTRY + 277
#define NATIONAL_DEX_WINGULL FINAL_GARTIC_ENTRY + 278
#define NATIONAL_DEX_PELIPPER FINAL_GARTIC_ENTRY + 279
#define NATIONAL_DEX_RALTS FINAL_GARTIC_ENTRY + 280
#define NATIONAL_DEX_KIRLIA FINAL_GARTIC_ENTRY + 281
#define NATIONAL_DEX_GARDEVOIR FINAL_GARTIC_ENTRY + 282
#define NATIONAL_DEX_SURSKIT FINAL_GARTIC_ENTRY + 283
#define NATIONAL_DEX_MASQUERAIN FINAL_GARTIC_ENTRY + 284
#define NATIONAL_DEX_SHROOMISH FINAL_GARTIC_ENTRY + 285
#define NATIONAL_DEX_BRELOOM FINAL_GARTIC_ENTRY + 286
#define NATIONAL_DEX_SLAKOTH FINAL_GARTIC_ENTRY + 287
#define NATIONAL_DEX_VIGOROTH FINAL_GARTIC_ENTRY + 288
#define NATIONAL_DEX_SLAKING FINAL_GARTIC_ENTRY + 289
#define NATIONAL_DEX_NINCADA FINAL_GARTIC_ENTRY + 290
#define NATIONAL_DEX_NINJASK FINAL_GARTIC_ENTRY + 291
#define NATIONAL_DEX_SHEDINJA FINAL_GARTIC_ENTRY + 292
#define NATIONAL_DEX_WHISMUR FINAL_GARTIC_ENTRY + 293
#define NATIONAL_DEX_LOUDRED FINAL_GARTIC_ENTRY + 294
#define NATIONAL_DEX_EXPLOUD FINAL_GARTIC_ENTRY + 295
#define NATIONAL_DEX_MAKUHITA FINAL_GARTIC_ENTRY + 296
#define NATIONAL_DEX_HARIYAMA FINAL_GARTIC_ENTRY + 297
#define NATIONAL_DEX_AZURILL FINAL_GARTIC_ENTRY + 298
#define NATIONAL_DEX_NOSEPASS FINAL_GARTIC_ENTRY + 299
#define NATIONAL_DEX_SKITTY FINAL_GARTIC_ENTRY + 300
#define NATIONAL_DEX_DELCATTY FINAL_GARTIC_ENTRY + 301
#define NATIONAL_DEX_SABLEYE FINAL_GARTIC_ENTRY + 302
#define NATIONAL_DEX_MAWILE FINAL_GARTIC_ENTRY + 303
#define NATIONAL_DEX_ARON FINAL_GARTIC_ENTRY + 304
#define NATIONAL_DEX_LAIRON FINAL_GARTIC_ENTRY + 305
#define NATIONAL_DEX_AGGRON FINAL_GARTIC_ENTRY + 306
#define NATIONAL_DEX_MEDITITE FINAL_GARTIC_ENTRY + 307
#define NATIONAL_DEX_MEDICHAM FINAL_GARTIC_ENTRY + 308
#define NATIONAL_DEX_ELECTRIKE FINAL_GARTIC_ENTRY + 309
#define NATIONAL_DEX_MANECTRIC FINAL_GARTIC_ENTRY + 310
#define NATIONAL_DEX_PLUSLE FINAL_GARTIC_ENTRY + 311
#define NATIONAL_DEX_MINUN FINAL_GARTIC_ENTRY + 312
#define NATIONAL_DEX_VOLBEAT FINAL_GARTIC_ENTRY + 313
#define NATIONAL_DEX_ILLUMISE FINAL_GARTIC_ENTRY + 314
#define NATIONAL_DEX_ROSELIA FINAL_GARTIC_ENTRY + 315
#define NATIONAL_DEX_GULPIN FINAL_GARTIC_ENTRY + 316
#define NATIONAL_DEX_SWALOT FINAL_GARTIC_ENTRY + 317
#define NATIONAL_DEX_CARVANHA FINAL_GARTIC_ENTRY + 318
#define NATIONAL_DEX_SHARPEDO FINAL_GARTIC_ENTRY + 319
#define NATIONAL_DEX_WAILMER FINAL_GARTIC_ENTRY + 320
#define NATIONAL_DEX_WAILORD FINAL_GARTIC_ENTRY + 321
#define NATIONAL_DEX_NUMEL FINAL_GARTIC_ENTRY + 322
#define NATIONAL_DEX_CAMERUPT FINAL_GARTIC_ENTRY + 323
#define NATIONAL_DEX_TORKOAL FINAL_GARTIC_ENTRY + 324
#define NATIONAL_DEX_SPOINK FINAL_GARTIC_ENTRY + 325
#define NATIONAL_DEX_GRUMPIG FINAL_GARTIC_ENTRY + 326
#define NATIONAL_DEX_SPINDA FINAL_GARTIC_ENTRY + 327
#define NATIONAL_DEX_TRAPINCH FINAL_GARTIC_ENTRY + 328
#define NATIONAL_DEX_VIBRAVA FINAL_GARTIC_ENTRY + 329
#define NATIONAL_DEX_FLYGON FINAL_GARTIC_ENTRY + 330
#define NATIONAL_DEX_CACNEA FINAL_GARTIC_ENTRY + 331
#define NATIONAL_DEX_CACTURNE FINAL_GARTIC_ENTRY + 332
#define NATIONAL_DEX_SWABLU FINAL_GARTIC_ENTRY + 333
#define NATIONAL_DEX_ALTARIA FINAL_GARTIC_ENTRY + 334
#define NATIONAL_DEX_ZANGOOSE FINAL_GARTIC_ENTRY + 335
#define NATIONAL_DEX_SEVIPER FINAL_GARTIC_ENTRY + 336
#define NATIONAL_DEX_LUNATONE FINAL_GARTIC_ENTRY + 337
#define NATIONAL_DEX_SOLROCK FINAL_GARTIC_ENTRY + 338
#define NATIONAL_DEX_BARBOACH FINAL_GARTIC_ENTRY + 339
#define NATIONAL_DEX_WHISCASH FINAL_GARTIC_ENTRY + 340
#define NATIONAL_DEX_CORPHISH FINAL_GARTIC_ENTRY + 341
#define NATIONAL_DEX_CRAWDAUNT FINAL_GARTIC_ENTRY + 342
#define NATIONAL_DEX_BALTOY FINAL_GARTIC_ENTRY + 343
#define NATIONAL_DEX_CLAYDOL FINAL_GARTIC_ENTRY + 344
#define NATIONAL_DEX_LILEEP FINAL_GARTIC_ENTRY + 345
#define NATIONAL_DEX_CRADILY FINAL_GARTIC_ENTRY + 346
#define NATIONAL_DEX_ANORITH FINAL_GARTIC_ENTRY + 347
#define NATIONAL_DEX_ARMALDO FINAL_GARTIC_ENTRY + 348
#define NATIONAL_DEX_FEEBAS FINAL_GARTIC_ENTRY + 349
#define NATIONAL_DEX_MILOTIC FINAL_GARTIC_ENTRY + 350
#define NATIONAL_DEX_CASTFORM FINAL_GARTIC_ENTRY + 351
#define NATIONAL_DEX_CASTFORM FINAL_GARTIC_ENTRY + 351
#define NATIONAL_DEX_CASTFORM FINAL_GARTIC_ENTRY + 351
#define NATIONAL_DEX_CASTFORM FINAL_GARTIC_ENTRY + 351
#define NATIONAL_DEX_KECLEON FINAL_GARTIC_ENTRY + 352
#define NATIONAL_DEX_SHUPPET FINAL_GARTIC_ENTRY + 353
#define NATIONAL_DEX_BANETTE FINAL_GARTIC_ENTRY + 354
#define NATIONAL_DEX_DUSKULL FINAL_GARTIC_ENTRY + 355
#define NATIONAL_DEX_DUSCLOPS FINAL_GARTIC_ENTRY + 356
#define NATIONAL_DEX_TROPIUS FINAL_GARTIC_ENTRY + 357
#define NATIONAL_DEX_CHIMECHO FINAL_GARTIC_ENTRY + 358
#define NATIONAL_DEX_ABSOL FINAL_GARTIC_ENTRY + 359
#define NATIONAL_DEX_WYNAUT FINAL_GARTIC_ENTRY + 360
#define NATIONAL_DEX_SNORUNT FINAL_GARTIC_ENTRY + 361
#define NATIONAL_DEX_GLALIE FINAL_GARTIC_ENTRY + 362
#define NATIONAL_DEX_SPHEAL FINAL_GARTIC_ENTRY + 363
#define NATIONAL_DEX_SEALEO FINAL_GARTIC_ENTRY + 364
#define NATIONAL_DEX_WALREIN FINAL_GARTIC_ENTRY + 365
#define NATIONAL_DEX_CLAMPERL FINAL_GARTIC_ENTRY + 366
#define NATIONAL_DEX_HUNTAIL FINAL_GARTIC_ENTRY + 367
#define NATIONAL_DEX_GOREBYSS FINAL_GARTIC_ENTRY + 368
#define NATIONAL_DEX_RELICANTH FINAL_GARTIC_ENTRY + 369
#define NATIONAL_DEX_LUVDISC FINAL_GARTIC_ENTRY + 370
#define NATIONAL_DEX_BAGON FINAL_GARTIC_ENTRY + 371
#define NATIONAL_DEX_SHELGON FINAL_GARTIC_ENTRY + 372
#define NATIONAL_DEX_SALAMENCE FINAL_GARTIC_ENTRY + 373
#define NATIONAL_DEX_BELDUM FINAL_GARTIC_ENTRY + 374
#define NATIONAL_DEX_METANG FINAL_GARTIC_ENTRY + 375
#define NATIONAL_DEX_METAGROSS FINAL_GARTIC_ENTRY + 376
#define NATIONAL_DEX_REGIROCK FINAL_GARTIC_ENTRY + 377
#define NATIONAL_DEX_REGICE FINAL_GARTIC_ENTRY + 378
#define NATIONAL_DEX_REGISTEEL FINAL_GARTIC_ENTRY + 379
#define NATIONAL_DEX_LATIAS FINAL_GARTIC_ENTRY + 380
#define NATIONAL_DEX_LATIOS FINAL_GARTIC_ENTRY + 381
#define NATIONAL_DEX_KYOGRE FINAL_GARTIC_ENTRY + 382
#define NATIONAL_DEX_GROUDON FINAL_GARTIC_ENTRY + 383
#define NATIONAL_DEX_RAYQUAZA FINAL_GARTIC_ENTRY + 384
#define NATIONAL_DEX_JIRACHI FINAL_GARTIC_ENTRY + 385
#define NATIONAL_DEX_DEOXYS FINAL_GARTIC_ENTRY + 386

//Sinnoh
#define NATIONAL_DEX_TURTWIG FINAL_GARTIC_ENTRY + 387
#define NATIONAL_DEX_GROTLE FINAL_GARTIC_ENTRY + 388
#define NATIONAL_DEX_TORTERRA FINAL_GARTIC_ENTRY + 389
#define NATIONAL_DEX_CHIMCHAR FINAL_GARTIC_ENTRY + 390
#define NATIONAL_DEX_MONFERNO FINAL_GARTIC_ENTRY + 391
#define NATIONAL_DEX_INFERNAPE FINAL_GARTIC_ENTRY + 392
#define NATIONAL_DEX_PIPLUP FINAL_GARTIC_ENTRY + 393
#define NATIONAL_DEX_PRINPLUP FINAL_GARTIC_ENTRY + 394
#define NATIONAL_DEX_EMPOLEON FINAL_GARTIC_ENTRY + 395
#define NATIONAL_DEX_STARLY FINAL_GARTIC_ENTRY + 396
#define NATIONAL_DEX_STARAVIA FINAL_GARTIC_ENTRY + 397
#define NATIONAL_DEX_STARAPTOR FINAL_GARTIC_ENTRY + 398
#define NATIONAL_DEX_BIDOOF FINAL_GARTIC_ENTRY + 399
#define NATIONAL_DEX_BIBAREL FINAL_GARTIC_ENTRY + 400
#define NATIONAL_DEX_KRICKETOT FINAL_GARTIC_ENTRY + 401
#define NATIONAL_DEX_KRICKETUNE FINAL_GARTIC_ENTRY + 402
#define NATIONAL_DEX_SHINX  FINAL_GARTIC_ENTRY + 403
#define NATIONAL_DEX_LUXIO  FINAL_GARTIC_ENTRY + 404
#define NATIONAL_DEX_LUXRAY FINAL_GARTIC_ENTRY + 405
#define NATIONAL_DEX_BUDEW FINAL_GARTIC_ENTRY + 406
#define NATIONAL_DEX_ROSERADE FINAL_GARTIC_ENTRY + 407
#define NATIONAL_DEX_CRANIDOS FINAL_GARTIC_ENTRY + 408
#define NATIONAL_DEX_RAMPARDOS FINAL_GARTIC_ENTRY + 409
#define NATIONAL_DEX_SHIELDON FINAL_GARTIC_ENTRY + 410
#define NATIONAL_DEX_BASTIODON FINAL_GARTIC_ENTRY + 411
#define NATIONAL_DEX_BURMY FINAL_GARTIC_ENTRY + 412
#define NATIONAL_DEX_WORMADAM FINAL_GARTIC_ENTRY + 413
#define NATIONAL_DEX_MOTHIM FINAL_GARTIC_ENTRY + 414
#define NATIONAL_DEX_COMBEE FINAL_GARTIC_ENTRY + 415
#define NATIONAL_DEX_VESPIQUEN FINAL_GARTIC_ENTRY + 416
#define NATIONAL_DEX_PACHIRISU FINAL_GARTIC_ENTRY + 417
#define NATIONAL_DEX_BUIZEL FINAL_GARTIC_ENTRY + 418
#define NATIONAL_DEX_FLOATZEL FINAL_GARTIC_ENTRY + 419
#define NATIONAL_DEX_CHERUBI FINAL_GARTIC_ENTRY + 420
#define NATIONAL_DEX_CHERRIM FINAL_GARTIC_ENTRY + 421
#define NATIONAL_DEX_SHELLOS FINAL_GARTIC_ENTRY + 422
#define NATIONAL_DEX_GASTRODON FINAL_GARTIC_ENTRY + 423
#define NATIONAL_DEX_AMBIPOM FINAL_GARTIC_ENTRY + 424
#define NATIONAL_DEX_DRIFLOON FINAL_GARTIC_ENTRY + 425
#define NATIONAL_DEX_DRIFBLIM FINAL_GARTIC_ENTRY + 426
#define NATIONAL_DEX_BUNEARY FINAL_GARTIC_ENTRY + 427
#define NATIONAL_DEX_LOPUNNY FINAL_GARTIC_ENTRY + 428
#define NATIONAL_DEX_MISMAGIUS FINAL_GARTIC_ENTRY + 429
#define NATIONAL_DEX_HONCHKROW FINAL_GARTIC_ENTRY + 430
#define NATIONAL_DEX_GLAMEOW FINAL_GARTIC_ENTRY + 431
#define NATIONAL_DEX_PURUGLY FINAL_GARTIC_ENTRY + 432
#define NATIONAL_DEX_CHINGLING FINAL_GARTIC_ENTRY + 433
#define NATIONAL_DEX_STUNKY FINAL_GARTIC_ENTRY + 434
#define NATIONAL_DEX_SKUNTANK FINAL_GARTIC_ENTRY + 435
#define NATIONAL_DEX_BRONZOR FINAL_GARTIC_ENTRY + 436
#define NATIONAL_DEX_BRONZONG FINAL_GARTIC_ENTRY + 437
#define NATIONAL_DEX_BONSLY FINAL_GARTIC_ENTRY + 438
#define NATIONAL_DEX_MIME_JR FINAL_GARTIC_ENTRY + 439
#define NATIONAL_DEX_HAPPINY FINAL_GARTIC_ENTRY + 440
#define NATIONAL_DEX_CHATOT FINAL_GARTIC_ENTRY + 441
#define NATIONAL_DEX_SPIRITOMB FINAL_GARTIC_ENTRY + 442
#define NATIONAL_DEX_GIBLE FINAL_GARTIC_ENTRY + 443
#define NATIONAL_DEX_GABITE FINAL_GARTIC_ENTRY + 444
#define NATIONAL_DEX_GARCHOMP FINAL_GARTIC_ENTRY + 445
#define NATIONAL_DEX_MUNCHLAX FINAL_GARTIC_ENTRY + 446
#define NATIONAL_DEX_RIOLU FINAL_GARTIC_ENTRY + 447
#define NATIONAL_DEX_LUCARIO FINAL_GARTIC_ENTRY + 448
#define NATIONAL_DEX_HIPPOPOTAS FINAL_GARTIC_ENTRY + 449
#define NATIONAL_DEX_HIPPOWDON FINAL_GARTIC_ENTRY + 450
#define NATIONAL_DEX_SKORUPI FINAL_GARTIC_ENTRY + 451
#define NATIONAL_DEX_DRAPION FINAL_GARTIC_ENTRY + 452
#define NATIONAL_DEX_CROAGUNK FINAL_GARTIC_ENTRY + 453
#define NATIONAL_DEX_TOXICROAK FINAL_GARTIC_ENTRY + 454
#define NATIONAL_DEX_CARNIVINE FINAL_GARTIC_ENTRY + 455
#define NATIONAL_DEX_FINNEON FINAL_GARTIC_ENTRY + 456
#define NATIONAL_DEX_LUMINEON FINAL_GARTIC_ENTRY + 457
#define NATIONAL_DEX_MANTYKE FINAL_GARTIC_ENTRY + 458
#define NATIONAL_DEX_SNOVER FINAL_GARTIC_ENTRY + 459
#define NATIONAL_DEX_ABOMASNOW FINAL_GARTIC_ENTRY + 460
#define NATIONAL_DEX_WEAVILE FINAL_GARTIC_ENTRY + 461
#define NATIONAL_DEX_MAGNEZONE FINAL_GARTIC_ENTRY + 462
#define NATIONAL_DEX_LICKILICKY FINAL_GARTIC_ENTRY + 463
#define NATIONAL_DEX_RHYPERIOR FINAL_GARTIC_ENTRY + 464
#define NATIONAL_DEX_TANGROWTH FINAL_GARTIC_ENTRY + 465
#define NATIONAL_DEX_ELECTIVIRE FINAL_GARTIC_ENTRY + 466
#define NATIONAL_DEX_MAGMORTAR FINAL_GARTIC_ENTRY + 467
#define NATIONAL_DEX_TOGEKISS FINAL_GARTIC_ENTRY + 468
#define NATIONAL_DEX_YANMEGA FINAL_GARTIC_ENTRY + 469
#define NATIONAL_DEX_LEAFEON FINAL_GARTIC_ENTRY + 470
#define NATIONAL_DEX_GLACEON FINAL_GARTIC_ENTRY + 471
#define NATIONAL_DEX_GLISCOR FINAL_GARTIC_ENTRY + 472
#define NATIONAL_DEX_MAMOSWINE FINAL_GARTIC_ENTRY + 473
#define NATIONAL_DEX_PORYGON_Z FINAL_GARTIC_ENTRY + 474
#define NATIONAL_DEX_GALLADE FINAL_GARTIC_ENTRY + 475
#define NATIONAL_DEX_PROBOPASS FINAL_GARTIC_ENTRY + 476
#define NATIONAL_DEX_DUSKNOIR FINAL_GARTIC_ENTRY + 477
#define NATIONAL_DEX_FROSLASS FINAL_GARTIC_ENTRY + 478
#define NATIONAL_DEX_ROTOM FINAL_GARTIC_ENTRY + 479
#define NATIONAL_DEX_UXIE FINAL_GARTIC_ENTRY + 480
#define NATIONAL_DEX_MESPRIT FINAL_GARTIC_ENTRY + 481
#define NATIONAL_DEX_AZELF FINAL_GARTIC_ENTRY + 482
#define NATIONAL_DEX_DIALGA FINAL_GARTIC_ENTRY + 483
#define NATIONAL_DEX_PALKIA FINAL_GARTIC_ENTRY + 484
#define NATIONAL_DEX_HEATRAN FINAL_GARTIC_ENTRY + 485
#define NATIONAL_DEX_REGIGIGAS FINAL_GARTIC_ENTRY + 486
#define NATIONAL_DEX_GIRATINA FINAL_GARTIC_ENTRY + 487
#define NATIONAL_DEX_CRESSELIA FINAL_GARTIC_ENTRY + 488
#define NATIONAL_DEX_PHIONE FINAL_GARTIC_ENTRY + 489
#define NATIONAL_DEX_MANAPHY FINAL_GARTIC_ENTRY + 490
#define NATIONAL_DEX_DARKRAI FINAL_GARTIC_ENTRY + 491
#define NATIONAL_DEX_SHAYMIN FINAL_GARTIC_ENTRY + 492
#define NATIONAL_DEX_ARCEUS FINAL_GARTIC_ENTRY + 493

//Unova
#define NATIONAL_DEX_VICTINI FINAL_GARTIC_ENTRY + 494
#define NATIONAL_DEX_SNIVY FINAL_GARTIC_ENTRY + 495
#define NATIONAL_DEX_SERVINE FINAL_GARTIC_ENTRY + 496
#define NATIONAL_DEX_SERPERIOR FINAL_GARTIC_ENTRY + 497
#define NATIONAL_DEX_TEPIG FINAL_GARTIC_ENTRY + 498
#define NATIONAL_DEX_PIGNITE FINAL_GARTIC_ENTRY + 499
#define NATIONAL_DEX_EMBOAR FINAL_GARTIC_ENTRY + 500
#define NATIONAL_DEX_OSHAWOTT FINAL_GARTIC_ENTRY + 501
#define NATIONAL_DEX_DEWOTT FINAL_GARTIC_ENTRY + 502
#define NATIONAL_DEX_SAMUROTT FINAL_GARTIC_ENTRY + 503
#define NATIONAL_DEX_PATRAT FINAL_GARTIC_ENTRY + 504
#define NATIONAL_DEX_WATCHOG FINAL_GARTIC_ENTRY + 505
#define NATIONAL_DEX_LILLIPUP FINAL_GARTIC_ENTRY + 506
#define NATIONAL_DEX_HERDIER FINAL_GARTIC_ENTRY + 507
#define NATIONAL_DEX_STOUTLAND FINAL_GARTIC_ENTRY + 508
#define NATIONAL_DEX_PURRLOIN FINAL_GARTIC_ENTRY + 509
#define NATIONAL_DEX_LIEPARD FINAL_GARTIC_ENTRY + 510
#define NATIONAL_DEX_PANSAGE FINAL_GARTIC_ENTRY + 511
#define NATIONAL_DEX_SIMISAGE FINAL_GARTIC_ENTRY + 512
#define NATIONAL_DEX_PANSEAR FINAL_GARTIC_ENTRY + 513
#define NATIONAL_DEX_SIMISEAR FINAL_GARTIC_ENTRY + 514
#define NATIONAL_DEX_PANPOUR FINAL_GARTIC_ENTRY + 515
#define NATIONAL_DEX_SIMIPOUR FINAL_GARTIC_ENTRY + 516
#define NATIONAL_DEX_MUNNA FINAL_GARTIC_ENTRY + 517
#define NATIONAL_DEX_MUSHARNA FINAL_GARTIC_ENTRY + 518
#define NATIONAL_DEX_PIDOVE FINAL_GARTIC_ENTRY + 519
#define NATIONAL_DEX_TRANQUILL FINAL_GARTIC_ENTRY + 520
#define NATIONAL_DEX_UNFEZANT FINAL_GARTIC_ENTRY + 521
#define NATIONAL_DEX_BLITZLE FINAL_GARTIC_ENTRY + 522
#define NATIONAL_DEX_ZEBSTRIKA FINAL_GARTIC_ENTRY + 523
#define NATIONAL_DEX_ROGGENROLA FINAL_GARTIC_ENTRY + 524
#define NATIONAL_DEX_BOLDORE FINAL_GARTIC_ENTRY + 525
#define NATIONAL_DEX_GIGALITH FINAL_GARTIC_ENTRY + 526
#define NATIONAL_DEX_WOOBAT FINAL_GARTIC_ENTRY + 527
#define NATIONAL_DEX_SWOOBAT FINAL_GARTIC_ENTRY + 528
#define NATIONAL_DEX_DRILBUR FINAL_GARTIC_ENTRY + 529
#define NATIONAL_DEX_EXCADRILL FINAL_GARTIC_ENTRY + 530
#define NATIONAL_DEX_AUDINO FINAL_GARTIC_ENTRY + 531
#define NATIONAL_DEX_TIMBURR FINAL_GARTIC_ENTRY + 532
#define NATIONAL_DEX_GURDURR FINAL_GARTIC_ENTRY + 533
#define NATIONAL_DEX_CONKELDURR FINAL_GARTIC_ENTRY + 534
#define NATIONAL_DEX_TYMPOLE FINAL_GARTIC_ENTRY + 535
#define NATIONAL_DEX_PALPITOAD FINAL_GARTIC_ENTRY + 536
#define NATIONAL_DEX_SEISMITOAD FINAL_GARTIC_ENTRY + 537
#define NATIONAL_DEX_THROH FINAL_GARTIC_ENTRY + 538
#define NATIONAL_DEX_SAWK FINAL_GARTIC_ENTRY + 539
#define NATIONAL_DEX_SEWADDLE FINAL_GARTIC_ENTRY + 540
#define NATIONAL_DEX_SWADLOON FINAL_GARTIC_ENTRY + 541
#define NATIONAL_DEX_LEAVANNY FINAL_GARTIC_ENTRY + 542
#define NATIONAL_DEX_VENIPEDE FINAL_GARTIC_ENTRY + 543
#define NATIONAL_DEX_WHIRLIPEDE FINAL_GARTIC_ENTRY + 544
#define NATIONAL_DEX_SCOLIPEDE FINAL_GARTIC_ENTRY + 545
#define NATIONAL_DEX_COTTONEE FINAL_GARTIC_ENTRY + 546
#define NATIONAL_DEX_WHIMSICOTT FINAL_GARTIC_ENTRY + 547
#define NATIONAL_DEX_PETILIL FINAL_GARTIC_ENTRY + 548
#define NATIONAL_DEX_LILLIGANT FINAL_GARTIC_ENTRY + 549
#define NATIONAL_DEX_BASCULIN FINAL_GARTIC_ENTRY + 550
#define NATIONAL_DEX_SANDILE FINAL_GARTIC_ENTRY + 551
#define NATIONAL_DEX_KROKOROK FINAL_GARTIC_ENTRY + 552
#define NATIONAL_DEX_KROOKODILE FINAL_GARTIC_ENTRY + 553
#define NATIONAL_DEX_DARUMAKA FINAL_GARTIC_ENTRY + 554
#define NATIONAL_DEX_DARMANITAN FINAL_GARTIC_ENTRY + 555
#define NATIONAL_DEX_MARACTUS FINAL_GARTIC_ENTRY + 556
#define NATIONAL_DEX_DWEBBLE FINAL_GARTIC_ENTRY + 557
#define NATIONAL_DEX_CRUSTLE FINAL_GARTIC_ENTRY + 558
#define NATIONAL_DEX_SCRAGGY FINAL_GARTIC_ENTRY + 559
#define NATIONAL_DEX_SCRAFTY FINAL_GARTIC_ENTRY + 560
#define NATIONAL_DEX_SIGILYPH FINAL_GARTIC_ENTRY + 561
#define NATIONAL_DEX_YAMASK FINAL_GARTIC_ENTRY + 562
#define NATIONAL_DEX_COFAGRIGUS FINAL_GARTIC_ENTRY + 563
#define NATIONAL_DEX_TIRTOUGA FINAL_GARTIC_ENTRY + 564
#define NATIONAL_DEX_CARRACOSTA FINAL_GARTIC_ENTRY + 565
#define NATIONAL_DEX_ARCHEN FINAL_GARTIC_ENTRY + 566
#define NATIONAL_DEX_ARCHEOPS FINAL_GARTIC_ENTRY + 567
#define NATIONAL_DEX_TRUBBISH FINAL_GARTIC_ENTRY + 568
#define NATIONAL_DEX_GARBODOR FINAL_GARTIC_ENTRY + 569
#define NATIONAL_DEX_ZORUA FINAL_GARTIC_ENTRY + 570
#define NATIONAL_DEX_ZOROARK FINAL_GARTIC_ENTRY + 571
#define NATIONAL_DEX_MINCCINO FINAL_GARTIC_ENTRY + 572
#define NATIONAL_DEX_CINCCINO FINAL_GARTIC_ENTRY + 573
#define NATIONAL_DEX_GOTHITA FINAL_GARTIC_ENTRY + 574
#define NATIONAL_DEX_GOTHORITA FINAL_GARTIC_ENTRY + 575
#define NATIONAL_DEX_GOTHITELLE FINAL_GARTIC_ENTRY + 576
#define NATIONAL_DEX_SOLOSIS FINAL_GARTIC_ENTRY + 577
#define NATIONAL_DEX_DUOSION FINAL_GARTIC_ENTRY + 578
#define NATIONAL_DEX_REUNICLUS FINAL_GARTIC_ENTRY + 579
#define NATIONAL_DEX_DUCKLETT FINAL_GARTIC_ENTRY + 580
#define NATIONAL_DEX_SWANNA FINAL_GARTIC_ENTRY + 581
#define NATIONAL_DEX_VANILLITE FINAL_GARTIC_ENTRY + 582
#define NATIONAL_DEX_VANILLISH FINAL_GARTIC_ENTRY + 583
#define NATIONAL_DEX_VANILLUXE FINAL_GARTIC_ENTRY + 584
#define NATIONAL_DEX_DEERLING FINAL_GARTIC_ENTRY + 585
#define NATIONAL_DEX_SAWSBUCK FINAL_GARTIC_ENTRY + 586
#define NATIONAL_DEX_EMOLGA FINAL_GARTIC_ENTRY + 587
#define NATIONAL_DEX_KARRABLAST FINAL_GARTIC_ENTRY + 588
#define NATIONAL_DEX_ESCAVALIER FINAL_GARTIC_ENTRY + 589
#define NATIONAL_DEX_FOONGUS FINAL_GARTIC_ENTRY + 590
#define NATIONAL_DEX_AMOONGUSS FINAL_GARTIC_ENTRY + 591
#define NATIONAL_DEX_FRILLISH FINAL_GARTIC_ENTRY + 592
#define NATIONAL_DEX_JELLICENT FINAL_GARTIC_ENTRY + 593
#define NATIONAL_DEX_ALOMOMOLA FINAL_GARTIC_ENTRY + 594
#define NATIONAL_DEX_JOLTIK FINAL_GARTIC_ENTRY + 595
#define NATIONAL_DEX_GALVANTULA FINAL_GARTIC_ENTRY + 596
#define NATIONAL_DEX_FERROSEED FINAL_GARTIC_ENTRY + 597
#define NATIONAL_DEX_FERROTHORN FINAL_GARTIC_ENTRY + 598
#define NATIONAL_DEX_KLINK FINAL_GARTIC_ENTRY + 599
#define NATIONAL_DEX_KLANG FINAL_GARTIC_ENTRY + 600
#define NATIONAL_DEX_KLINKLANG FINAL_GARTIC_ENTRY + 601
#define NATIONAL_DEX_TYNAMO FINAL_GARTIC_ENTRY + 602
#define NATIONAL_DEX_EELEKTRIK FINAL_GARTIC_ENTRY + 603
#define NATIONAL_DEX_EELEKTROSS FINAL_GARTIC_ENTRY + 604
#define NATIONAL_DEX_ELGYEM FINAL_GARTIC_ENTRY + 605
#define NATIONAL_DEX_BEHEEYEM FINAL_GARTIC_ENTRY + 606
#define NATIONAL_DEX_LITWICK FINAL_GARTIC_ENTRY + 607
#define NATIONAL_DEX_LAMPENT FINAL_GARTIC_ENTRY + 608
#define NATIONAL_DEX_CHANDELURE FINAL_GARTIC_ENTRY + 609
#define NATIONAL_DEX_AXEW FINAL_GARTIC_ENTRY + 610
#define NATIONAL_DEX_FRAXURE FINAL_GARTIC_ENTRY + 611
#define NATIONAL_DEX_HAXORUS FINAL_GARTIC_ENTRY + 612
#define NATIONAL_DEX_CUBCHOO FINAL_GARTIC_ENTRY + 613
#define NATIONAL_DEX_BEARTIC FINAL_GARTIC_ENTRY + 614
#define NATIONAL_DEX_CRYOGONAL FINAL_GARTIC_ENTRY + 615
#define NATIONAL_DEX_SHELMET FINAL_GARTIC_ENTRY + 616
#define NATIONAL_DEX_ACCELGOR FINAL_GARTIC_ENTRY + 617
#define NATIONAL_DEX_STUNFISK FINAL_GARTIC_ENTRY + 618
#define NATIONAL_DEX_MIENFOO FINAL_GARTIC_ENTRY + 619
#define NATIONAL_DEX_MIENSHAO FINAL_GARTIC_ENTRY + 620
#define NATIONAL_DEX_DRUDDIGON FINAL_GARTIC_ENTRY + 621
#define NATIONAL_DEX_GOLETT FINAL_GARTIC_ENTRY + 622
#define NATIONAL_DEX_GOLURK FINAL_GARTIC_ENTRY + 623
#define NATIONAL_DEX_PAWNIARD FINAL_GARTIC_ENTRY + 624
#define NATIONAL_DEX_BISHARP FINAL_GARTIC_ENTRY + 625
#define NATIONAL_DEX_BOUFFALANT FINAL_GARTIC_ENTRY + 626
#define NATIONAL_DEX_RUFFLET FINAL_GARTIC_ENTRY + 627
#define NATIONAL_DEX_BRAVIARY FINAL_GARTIC_ENTRY + 628
#define NATIONAL_DEX_VULLABY FINAL_GARTIC_ENTRY + 629
#define NATIONAL_DEX_MANDIBUZZ FINAL_GARTIC_ENTRY + 630
#define NATIONAL_DEX_HEATMOR FINAL_GARTIC_ENTRY + 631
#define NATIONAL_DEX_DURANT FINAL_GARTIC_ENTRY + 632
#define NATIONAL_DEX_DEINO FINAL_GARTIC_ENTRY + 633
#define NATIONAL_DEX_ZWEILOUS FINAL_GARTIC_ENTRY + 634
#define NATIONAL_DEX_HYDREIGON FINAL_GARTIC_ENTRY + 635
#define NATIONAL_DEX_LARVESTA FINAL_GARTIC_ENTRY + 636
#define NATIONAL_DEX_VOLCARONA FINAL_GARTIC_ENTRY + 637
#define NATIONAL_DEX_COBALION FINAL_GARTIC_ENTRY + 638
#define NATIONAL_DEX_TERRAKION FINAL_GARTIC_ENTRY + 639
#define NATIONAL_DEX_VIRIZION FINAL_GARTIC_ENTRY + 640
#define NATIONAL_DEX_TORNADUS FINAL_GARTIC_ENTRY + 641
#define NATIONAL_DEX_THUNDURUS FINAL_GARTIC_ENTRY + 642
#define NATIONAL_DEX_RESHIRAM FINAL_GARTIC_ENTRY + 643
#define NATIONAL_DEX_ZEKROM FINAL_GARTIC_ENTRY + 644
#define NATIONAL_DEX_LANDORUS FINAL_GARTIC_ENTRY + 645
#define NATIONAL_DEX_KYUREM FINAL_GARTIC_ENTRY + 646
#define NATIONAL_DEX_KELDEO FINAL_GARTIC_ENTRY + 647
#define NATIONAL_DEX_MELOETTA FINAL_GARTIC_ENTRY + 648
#define NATIONAL_DEX_GENESECT FINAL_GARTIC_ENTRY + 649

//Kalos
#define NATIONAL_DEX_CHESPIN FINAL_GARTIC_ENTRY + 650
#define NATIONAL_DEX_QUILLADIN FINAL_GARTIC_ENTRY + 651
#define NATIONAL_DEX_CHESNAUGHT FINAL_GARTIC_ENTRY + 652
#define NATIONAL_DEX_FENNEKIN FINAL_GARTIC_ENTRY + 653
#define NATIONAL_DEX_BRAIXEN FINAL_GARTIC_ENTRY + 654
#define NATIONAL_DEX_DELPHOX FINAL_GARTIC_ENTRY + 655
#define NATIONAL_DEX_FROAKIE FINAL_GARTIC_ENTRY + 656
#define NATIONAL_DEX_FROGADIER FINAL_GARTIC_ENTRY + 657
#define NATIONAL_DEX_GRENINJA FINAL_GARTIC_ENTRY + 658
#define NATIONAL_DEX_BUNNELBY FINAL_GARTIC_ENTRY + 659
#define NATIONAL_DEX_DIGGERSBY FINAL_GARTIC_ENTRY + 660
#define NATIONAL_DEX_FLETCHLING FINAL_GARTIC_ENTRY + 661
#define NATIONAL_DEX_FLETCHINDER FINAL_GARTIC_ENTRY + 662
#define NATIONAL_DEX_TALONFLAME FINAL_GARTIC_ENTRY + 663
#define NATIONAL_DEX_SCATTERBUG FINAL_GARTIC_ENTRY + 664
#define NATIONAL_DEX_SPEWPA FINAL_GARTIC_ENTRY + 665
#define NATIONAL_DEX_VIVILLON FINAL_GARTIC_ENTRY + 666
#define NATIONAL_DEX_LITLEO FINAL_GARTIC_ENTRY + 667
#define NATIONAL_DEX_PYROAR FINAL_GARTIC_ENTRY + 668
#define NATIONAL_DEX_FLABEBE FINAL_GARTIC_ENTRY + 669
#define NATIONAL_DEX_FLOETTE FINAL_GARTIC_ENTRY + 670
#define NATIONAL_DEX_FLORGES FINAL_GARTIC_ENTRY + 671
#define NATIONAL_DEX_SKIDDO FINAL_GARTIC_ENTRY + 672
#define NATIONAL_DEX_GOGOAT FINAL_GARTIC_ENTRY + 673
#define NATIONAL_DEX_PANCHAM FINAL_GARTIC_ENTRY + 674
#define NATIONAL_DEX_PANGORO FINAL_GARTIC_ENTRY + 675
#define NATIONAL_DEX_FURFROU FINAL_GARTIC_ENTRY + 676
#define NATIONAL_DEX_ESPURR FINAL_GARTIC_ENTRY + 677
#define NATIONAL_DEX_MEOWSTIC FINAL_GARTIC_ENTRY + 678
#define NATIONAL_DEX_HONEDGE FINAL_GARTIC_ENTRY + 679
#define NATIONAL_DEX_DOUBLADE FINAL_GARTIC_ENTRY + 680
#define NATIONAL_DEX_AEGISLASH FINAL_GARTIC_ENTRY + 681
#define NATIONAL_DEX_SPRITZEE FINAL_GARTIC_ENTRY + 682
#define NATIONAL_DEX_AROMATISSE FINAL_GARTIC_ENTRY + 683
#define NATIONAL_DEX_SWIRLIX FINAL_GARTIC_ENTRY + 684
#define NATIONAL_DEX_SLURPUFF FINAL_GARTIC_ENTRY + 685
#define NATIONAL_DEX_INKAY FINAL_GARTIC_ENTRY + 686
#define NATIONAL_DEX_MALAMAR FINAL_GARTIC_ENTRY + 687
#define NATIONAL_DEX_BINACLE FINAL_GARTIC_ENTRY + 688
#define NATIONAL_DEX_BARBARACLE FINAL_GARTIC_ENTRY + 689
#define NATIONAL_DEX_SKRELP FINAL_GARTIC_ENTRY + 690
#define NATIONAL_DEX_DRAGALGE FINAL_GARTIC_ENTRY + 691
#define NATIONAL_DEX_CLAUNCHER FINAL_GARTIC_ENTRY + 692
#define NATIONAL_DEX_CLAWITZER FINAL_GARTIC_ENTRY + 693
#define NATIONAL_DEX_HELIOPTILE FINAL_GARTIC_ENTRY + 694
#define NATIONAL_DEX_HELIOLISK FINAL_GARTIC_ENTRY + 695
#define NATIONAL_DEX_TYRUNT FINAL_GARTIC_ENTRY + 696
#define NATIONAL_DEX_TYRANTRUM FINAL_GARTIC_ENTRY + 697
#define NATIONAL_DEX_AMAURA FINAL_GARTIC_ENTRY + 698
#define NATIONAL_DEX_AURORUS FINAL_GARTIC_ENTRY + 699
#define NATIONAL_DEX_SYLVEON FINAL_GARTIC_ENTRY + 700
#define NATIONAL_DEX_HAWLUCHA FINAL_GARTIC_ENTRY + 701
#define NATIONAL_DEX_DEDENNE FINAL_GARTIC_ENTRY + 702
#define NATIONAL_DEX_CARBINK FINAL_GARTIC_ENTRY + 703
#define NATIONAL_DEX_GOOMY FINAL_GARTIC_ENTRY + 704
#define NATIONAL_DEX_SLIGGOO FINAL_GARTIC_ENTRY + 705
#define NATIONAL_DEX_GOODRA FINAL_GARTIC_ENTRY + 706
#define NATIONAL_DEX_KLEFKI FINAL_GARTIC_ENTRY + 707
#define NATIONAL_DEX_PHANTUMP FINAL_GARTIC_ENTRY + 708
#define NATIONAL_DEX_TREVENANT FINAL_GARTIC_ENTRY + 709
#define NATIONAL_DEX_PUMPKABOO FINAL_GARTIC_ENTRY + 710
#define NATIONAL_DEX_GOURGEIST FINAL_GARTIC_ENTRY + 711
#define NATIONAL_DEX_BERGMITE FINAL_GARTIC_ENTRY + 712
#define NATIONAL_DEX_AVALUGG FINAL_GARTIC_ENTRY + 713
#define NATIONAL_DEX_NOIBAT FINAL_GARTIC_ENTRY + 714
#define NATIONAL_DEX_NOIVERN FINAL_GARTIC_ENTRY + 715
#define NATIONAL_DEX_XERNEAS FINAL_GARTIC_ENTRY + 716
#define NATIONAL_DEX_YVELTAL FINAL_GARTIC_ENTRY + 717
#define NATIONAL_DEX_ZYGARDE FINAL_GARTIC_ENTRY + 718
#define NATIONAL_DEX_DIANCIE FINAL_GARTIC_ENTRY + 719
#define NATIONAL_DEX_HOOPA FINAL_GARTIC_ENTRY + 720
#define NATIONAL_DEX_VOLCANION FINAL_GARTIC_ENTRY + 721

//Alola
#define NATIONAL_DEX_ROWLET FINAL_GARTIC_ENTRY + 722
#define NATIONAL_DEX_DARTRIX FINAL_GARTIC_ENTRY + 723
#define NATIONAL_DEX_DECIDUEYE FINAL_GARTIC_ENTRY + 724
#define NATIONAL_DEX_LITTEN FINAL_GARTIC_ENTRY + 725
#define NATIONAL_DEX_TORRACAT FINAL_GARTIC_ENTRY + 726
#define NATIONAL_DEX_INCINEROAR FINAL_GARTIC_ENTRY + 727
#define NATIONAL_DEX_POPPLIO FINAL_GARTIC_ENTRY + 728
#define NATIONAL_DEX_BRIONNE FINAL_GARTIC_ENTRY + 729
#define NATIONAL_DEX_PRIMARINA FINAL_GARTIC_ENTRY + 730
#define NATIONAL_DEX_PIKIPEK FINAL_GARTIC_ENTRY + 731
#define NATIONAL_DEX_TRUMBEAK FINAL_GARTIC_ENTRY + 732
#define NATIONAL_DEX_TOUCANNON FINAL_GARTIC_ENTRY + 733
#define NATIONAL_DEX_YUNGOOS FINAL_GARTIC_ENTRY + 734
#define NATIONAL_DEX_GUMSHOOS FINAL_GARTIC_ENTRY + 735
#define NATIONAL_DEX_GRUBBIN FINAL_GARTIC_ENTRY + 736
#define NATIONAL_DEX_CHARJABUG FINAL_GARTIC_ENTRY + 737
#define NATIONAL_DEX_VIKAVOLT FINAL_GARTIC_ENTRY + 738
#define NATIONAL_DEX_CRABRAWLER FINAL_GARTIC_ENTRY + 739
#define NATIONAL_DEX_CRABOMINABLE FINAL_GARTIC_ENTRY + 740
#define NATIONAL_DEX_ORICORIO FINAL_GARTIC_ENTRY + 741
#define NATIONAL_DEX_CUTIEFLY FINAL_GARTIC_ENTRY + 742
#define NATIONAL_DEX_RIBOMBEE FINAL_GARTIC_ENTRY + 743
#define NATIONAL_DEX_ROCKRUFF FINAL_GARTIC_ENTRY + 744
#define NATIONAL_DEX_LYCANROC FINAL_GARTIC_ENTRY + 745
#define NATIONAL_DEX_WISHIWASHI FINAL_GARTIC_ENTRY + 746
#define NATIONAL_DEX_MAREANIE FINAL_GARTIC_ENTRY + 747
#define NATIONAL_DEX_TOXAPEX FINAL_GARTIC_ENTRY + 748
#define NATIONAL_DEX_MUDBRAY FINAL_GARTIC_ENTRY + 749
#define NATIONAL_DEX_MUDSDALE FINAL_GARTIC_ENTRY + 750
#define NATIONAL_DEX_DEWPIDER FINAL_GARTIC_ENTRY + 751
#define NATIONAL_DEX_ARAQUANID FINAL_GARTIC_ENTRY + 752
#define NATIONAL_DEX_FOMANTIS FINAL_GARTIC_ENTRY + 753
#define NATIONAL_DEX_LURANTIS FINAL_GARTIC_ENTRY + 754
#define NATIONAL_DEX_MORELULL FINAL_GARTIC_ENTRY + 755
#define NATIONAL_DEX_SHIINOTIC FINAL_GARTIC_ENTRY + 756
#define NATIONAL_DEX_SALANDIT FINAL_GARTIC_ENTRY + 757
#define NATIONAL_DEX_SALAZZLE FINAL_GARTIC_ENTRY + 758
#define NATIONAL_DEX_STUFFUL FINAL_GARTIC_ENTRY + 759
#define NATIONAL_DEX_BEWEAR FINAL_GARTIC_ENTRY + 760
#define NATIONAL_DEX_BOUNSWEET FINAL_GARTIC_ENTRY + 761
#define NATIONAL_DEX_STEENEE FINAL_GARTIC_ENTRY + 762
#define NATIONAL_DEX_TSAREENA FINAL_GARTIC_ENTRY + 763
#define NATIONAL_DEX_COMFEY FINAL_GARTIC_ENTRY + 764
#define NATIONAL_DEX_ORANGURU FINAL_GARTIC_ENTRY + 765
#define NATIONAL_DEX_PASSIMIAN FINAL_GARTIC_ENTRY + 766
#define NATIONAL_DEX_WIMPOD FINAL_GARTIC_ENTRY + 767
#define NATIONAL_DEX_GOLISOPOD FINAL_GARTIC_ENTRY + 768
#define NATIONAL_DEX_SANDYGAST FINAL_GARTIC_ENTRY + 769
#define NATIONAL_DEX_PALOSSAND FINAL_GARTIC_ENTRY + 770
#define NATIONAL_DEX_PYUKUMUKU FINAL_GARTIC_ENTRY + 771
#define NATIONAL_DEX_TYPE_NULL FINAL_GARTIC_ENTRY + 772
#define NATIONAL_DEX_SILVALLY FINAL_GARTIC_ENTRY + 773
#define NATIONAL_DEX_MINIOR FINAL_GARTIC_ENTRY + 774
#define NATIONAL_DEX_KOMALA FINAL_GARTIC_ENTRY + 775
#define NATIONAL_DEX_TURTONATOR FINAL_GARTIC_ENTRY + 776
#define NATIONAL_DEX_TOGEDEMARU FINAL_GARTIC_ENTRY + 777
#define NATIONAL_DEX_MIMIKYU FINAL_GARTIC_ENTRY + 778
#define NATIONAL_DEX_BRUXISH FINAL_GARTIC_ENTRY + 779
#define NATIONAL_DEX_DRAMPA FINAL_GARTIC_ENTRY + 780
#define NATIONAL_DEX_DHELMISE FINAL_GARTIC_ENTRY + 781
#define NATIONAL_DEX_JANGMO_O FINAL_GARTIC_ENTRY + 782
#define NATIONAL_DEX_HAKAMO_O FINAL_GARTIC_ENTRY + 783
#define NATIONAL_DEX_KOMMO_O FINAL_GARTIC_ENTRY + 784
#define NATIONAL_DEX_TAPU_KOKO FINAL_GARTIC_ENTRY + 785
#define NATIONAL_DEX_TAPU_LELE FINAL_GARTIC_ENTRY + 786
#define NATIONAL_DEX_TAPU_BULU FINAL_GARTIC_ENTRY + 787
#define NATIONAL_DEX_TAPU_FINI FINAL_GARTIC_ENTRY + 788
#define NATIONAL_DEX_COSMOG FINAL_GARTIC_ENTRY + 789
#define NATIONAL_DEX_COSMOEM FINAL_GARTIC_ENTRY + 790
#define NATIONAL_DEX_SOLGALEO FINAL_GARTIC_ENTRY + 791
#define NATIONAL_DEX_LUNALA FINAL_GARTIC_ENTRY + 792
#define NATIONAL_DEX_NIHILEGO FINAL_GARTIC_ENTRY + 793
#define NATIONAL_DEX_BUZZWOLE FINAL_GARTIC_ENTRY + 794
#define NATIONAL_DEX_PHEROMOSA FINAL_GARTIC_ENTRY + 795
#define NATIONAL_DEX_XURKITREE FINAL_GARTIC_ENTRY + 796
#define NATIONAL_DEX_CELESTEELA FINAL_GARTIC_ENTRY + 797
#define NATIONAL_DEX_KARTANA FINAL_GARTIC_ENTRY + 798
#define NATIONAL_DEX_GUZZLORD FINAL_GARTIC_ENTRY + 799
#define NATIONAL_DEX_NECROZMA FINAL_GARTIC_ENTRY + 800
#define NATIONAL_DEX_MAGEARNA FINAL_GARTIC_ENTRY + 801
#define NATIONAL_DEX_MARSHADOW FINAL_GARTIC_ENTRY + 802
#define NATIONAL_DEX_POIPOLE FINAL_GARTIC_ENTRY + 803
#define NATIONAL_DEX_NAGANADEL FINAL_GARTIC_ENTRY + 804
#define NATIONAL_DEX_STAKATAKA FINAL_GARTIC_ENTRY + 805
#define NATIONAL_DEX_BLACEPHALON FINAL_GARTIC_ENTRY + 806
#define NATIONAL_DEX_ZERAORA FINAL_GARTIC_ENTRY + 807

//Let's Go
#define NATIONAL_DEX_MELTAN FINAL_GARTIC_ENTRY + 808
#define NATIONAL_DEX_MELMETAL FINAL_GARTIC_ENTRY + 809

//Sword & Shield
#define NATIONAL_DEX_GROOKEY FINAL_GARTIC_ENTRY + 810
#define NATIONAL_DEX_THWACKEY FINAL_GARTIC_ENTRY + 811
#define NATIONAL_DEX_RILLABOOM FINAL_GARTIC_ENTRY + 812
#define NATIONAL_DEX_SCORBUNNY FINAL_GARTIC_ENTRY + 813
#define NATIONAL_DEX_RABOOT FINAL_GARTIC_ENTRY + 814
#define NATIONAL_DEX_CINDERACE FINAL_GARTIC_ENTRY + 815
#define NATIONAL_DEX_SOBBLE FINAL_GARTIC_ENTRY + 816
#define NATIONAL_DEX_DRIZZILE FINAL_GARTIC_ENTRY + 817
#define NATIONAL_DEX_INTELEON FINAL_GARTIC_ENTRY + 818
#define NATIONAL_DEX_SKWOVET FINAL_GARTIC_ENTRY + 819
#define NATIONAL_DEX_GREEDENT FINAL_GARTIC_ENTRY + 820
#define NATIONAL_DEX_ROOKIDEE FINAL_GARTIC_ENTRY + 821
#define NATIONAL_DEX_CORVISQUIRE FINAL_GARTIC_ENTRY + 822
#define NATIONAL_DEX_CORVIKNIGHT FINAL_GARTIC_ENTRY + 823
#define NATIONAL_DEX_BLIPBUG FINAL_GARTIC_ENTRY + 824
#define NATIONAL_DEX_DOTTLER FINAL_GARTIC_ENTRY + 825
#define NATIONAL_DEX_ORBEETLE FINAL_GARTIC_ENTRY + 826
#define NATIONAL_DEX_NICKIT FINAL_GARTIC_ENTRY + 827
#define NATIONAL_DEX_THIEVUL FINAL_GARTIC_ENTRY + 828
#define NATIONAL_DEX_GOSSIFLEUR FINAL_GARTIC_ENTRY + 829
#define NATIONAL_DEX_ELDEGOSS FINAL_GARTIC_ENTRY + 830
#define NATIONAL_DEX_WOOLOO FINAL_GARTIC_ENTRY + 831
#define NATIONAL_DEX_DUBWOOL FINAL_GARTIC_ENTRY + 832
#define NATIONAL_DEX_CHEWTLE FINAL_GARTIC_ENTRY + 833
#define NATIONAL_DEX_DREDNAW FINAL_GARTIC_ENTRY + 834
#define NATIONAL_DEX_YAMPER FINAL_GARTIC_ENTRY + 835
#define NATIONAL_DEX_BOLTUND FINAL_GARTIC_ENTRY + 836
#define NATIONAL_DEX_ROLYCOLY FINAL_GARTIC_ENTRY + 837
#define NATIONAL_DEX_CARKOL FINAL_GARTIC_ENTRY + 838
#define NATIONAL_DEX_COALOSSAL FINAL_GARTIC_ENTRY + 839
#define NATIONAL_DEX_APPLIN FINAL_GARTIC_ENTRY + 840
#define NATIONAL_DEX_FLAPPLE FINAL_GARTIC_ENTRY + 841
#define NATIONAL_DEX_APPLETUN FINAL_GARTIC_ENTRY + 842
#define NATIONAL_DEX_SILICOBRA FINAL_GARTIC_ENTRY + 843
#define NATIONAL_DEX_SANDACONDA FINAL_GARTIC_ENTRY + 844
#define NATIONAL_DEX_CRAMORANT FINAL_GARTIC_ENTRY + 845
#define NATIONAL_DEX_ARROKUDA FINAL_GARTIC_ENTRY + 846
#define NATIONAL_DEX_BARRASKEWDA FINAL_GARTIC_ENTRY + 847
#define NATIONAL_DEX_TOXEL FINAL_GARTIC_ENTRY + 848
#define NATIONAL_DEX_TOXTRICITY FINAL_GARTIC_ENTRY + 849
#define NATIONAL_DEX_SIZZLIPEDE FINAL_GARTIC_ENTRY + 850
#define NATIONAL_DEX_CENTISKORCH FINAL_GARTIC_ENTRY + 851
#define NATIONAL_DEX_CLOBBOPUS FINAL_GARTIC_ENTRY + 852
#define NATIONAL_DEX_GRAPPLOCT FINAL_GARTIC_ENTRY + 853
#define NATIONAL_DEX_SINISTEA FINAL_GARTIC_ENTRY + 854
#define NATIONAL_DEX_POLTEAGEIST FINAL_GARTIC_ENTRY + 855
#define NATIONAL_DEX_HATENNA FINAL_GARTIC_ENTRY + 856
#define NATIONAL_DEX_HATTREM FINAL_GARTIC_ENTRY + 857
#define NATIONAL_DEX_HATTERENE FINAL_GARTIC_ENTRY + 858
#define NATIONAL_DEX_IMPIDIMP FINAL_GARTIC_ENTRY + 859
#define NATIONAL_DEX_MORGREM FINAL_GARTIC_ENTRY + 860
#define NATIONAL_DEX_GRIMMSNARL FINAL_GARTIC_ENTRY + 861
#define NATIONAL_DEX_OBSTAGOON FINAL_GARTIC_ENTRY + 862
#define NATIONAL_DEX_PERRSERKER FINAL_GARTIC_ENTRY + 863
#define NATIONAL_DEX_CURSOLA FINAL_GARTIC_ENTRY + 864
#define NATIONAL_DEX_SIRFETCHD FINAL_GARTIC_ENTRY + 865
#define NATIONAL_DEX_MR_RIME FINAL_GARTIC_ENTRY + 866
#define NATIONAL_DEX_RUNERIGUS FINAL_GARTIC_ENTRY + 867
#define NATIONAL_DEX_MILCERY FINAL_GARTIC_ENTRY + 868
#define NATIONAL_DEX_ALCREMIE FINAL_GARTIC_ENTRY + 869
#define NATIONAL_DEX_FALINKS FINAL_GARTIC_ENTRY + 870
#define NATIONAL_DEX_PINCURCHIN FINAL_GARTIC_ENTRY + 871
#define NATIONAL_DEX_SNOM FINAL_GARTIC_ENTRY + 872
#define NATIONAL_DEX_FROSMOTH FINAL_GARTIC_ENTRY + 873
#define NATIONAL_DEX_STONJOURNER FINAL_GARTIC_ENTRY + 874
#define NATIONAL_DEX_EISCUE FINAL_GARTIC_ENTRY + 875
#define NATIONAL_DEX_INDEEDEE FINAL_GARTIC_ENTRY + 876
#define NATIONAL_DEX_MORPEKO FINAL_GARTIC_ENTRY + 877
#define NATIONAL_DEX_CUFANT FINAL_GARTIC_ENTRY + 878
#define NATIONAL_DEX_COPPERAJAH FINAL_GARTIC_ENTRY + 879
#define NATIONAL_DEX_DRACOZOLT FINAL_GARTIC_ENTRY + 880
#define NATIONAL_DEX_ARCTOZOLT FINAL_GARTIC_ENTRY + 881
#define NATIONAL_DEX_DRACOVISH FINAL_GARTIC_ENTRY + 882
#define NATIONAL_DEX_ARCTOVISH FINAL_GARTIC_ENTRY + 883
#define NATIONAL_DEX_DURALUDON FINAL_GARTIC_ENTRY + 884
#define NATIONAL_DEX_DREEPY FINAL_GARTIC_ENTRY + 885
#define NATIONAL_DEX_DRAKLOAK FINAL_GARTIC_ENTRY + 886
#define NATIONAL_DEX_DRAGAPULT FINAL_GARTIC_ENTRY + 887
#define NATIONAL_DEX_ZACIAN FINAL_GARTIC_ENTRY + 888
#define NATIONAL_DEX_ZAMAZENTA FINAL_GARTIC_ENTRY + 889
#define NATIONAL_DEX_ETERNATUS FINAL_GARTIC_ENTRY + 890
#define NATIONAL_DEX_KUBFU FINAL_GARTIC_ENTRY + 891
#define NATIONAL_DEX_URSHIFU FINAL_GARTIC_ENTRY + 892
#define NATIONAL_DEX_ZARUDE FINAL_GARTIC_ENTRY + 893
#define NATIONAL_DEX_REGIELEKI FINAL_GARTIC_ENTRY + 894
#define NATIONAL_DEX_REGIDRAGO FINAL_GARTIC_ENTRY + 895
#define NATIONAL_DEX_GLASTRIER FINAL_GARTIC_ENTRY + 896
#define NATIONAL_DEX_SPECTRIER FINAL_GARTIC_ENTRY + 897
#define NATIONAL_DEX_CALYREX FINAL_GARTIC_ENTRY + 898

#define FINAL_DEX_ENTRY NATIONAL_DEX_CALYREX //Not +1 b/c used like this for some asm
#define NATIONAL_DEX_COUNT FINAL_DEX_ENTRY + 1

extern const u8 DEX_ENTRY_TURTWIG[];
extern const u8 DEX_ENTRY_GROTLE[];
extern const u8 DEX_ENTRY_TORTERRA[];
extern const u8 DEX_ENTRY_CHIMCHAR[];
extern const u8 DEX_ENTRY_MONFERNO[];
extern const u8 DEX_ENTRY_INFERNAPE[];
extern const u8 DEX_ENTRY_PIPLUP[];
extern const u8 DEX_ENTRY_PRINPLUP[];
extern const u8 DEX_ENTRY_EMPOLEON[];
extern const u8 DEX_ENTRY_STARLY[];
extern const u8 DEX_ENTRY_STARAVIA[];
extern const u8 DEX_ENTRY_STARAPTOR[];
extern const u8 DEX_ENTRY_BIDOOF[];
extern const u8 DEX_ENTRY_BIBAREL[];
extern const u8 DEX_ENTRY_KRICKETOT[];
extern const u8 DEX_ENTRY_KRICKETUNE[];
extern const u8 DEX_ENTRY_SHINX[];
extern const u8 DEX_ENTRY_LUXIO[];
extern const u8 DEX_ENTRY_LUXRAY[];
extern const u8 DEX_ENTRY_BUDEW[];
extern const u8 DEX_ENTRY_ROSERADE[];
extern const u8 DEX_ENTRY_CRANIDOS[];
extern const u8 DEX_ENTRY_RAMPARDOS[];
extern const u8 DEX_ENTRY_SHIELDON[];
extern const u8 DEX_ENTRY_BASTIODON[];
extern const u8 DEX_ENTRY_BURMY[];
extern const u8 DEX_ENTRY_WORMADAM[];
extern const u8 DEX_ENTRY_MOTHIM[];
extern const u8 DEX_ENTRY_COMBEE[];
extern const u8 DEX_ENTRY_VESPIQUEN[];
extern const u8 DEX_ENTRY_PACHIRISU[];
extern const u8 DEX_ENTRY_BUIZEL[];
extern const u8 DEX_ENTRY_FLOATZEL[];
extern const u8 DEX_ENTRY_CHERUBI[];
extern const u8 DEX_ENTRY_CHERRIM[];
extern const u8 DEX_ENTRY_SHELLOS[];
extern const u8 DEX_ENTRY_GASTRODON[];
extern const u8 DEX_ENTRY_AMBIPOM[];
extern const u8 DEX_ENTRY_DRIFLOON[];
extern const u8 DEX_ENTRY_DRIFBLIM[];
extern const u8 DEX_ENTRY_BUNEARY[];
extern const u8 DEX_ENTRY_LOPUNNY[];
extern const u8 DEX_ENTRY_MISMAGIUS[];
extern const u8 DEX_ENTRY_HONCHKROW[];
extern const u8 DEX_ENTRY_GLAMEOW[];
extern const u8 DEX_ENTRY_PURUGLY[];
extern const u8 DEX_ENTRY_CHINGLING[];
extern const u8 DEX_ENTRY_STUNKY[];
extern const u8 DEX_ENTRY_SKUNTANK[];
extern const u8 DEX_ENTRY_BRONZOR[];
extern const u8 DEX_ENTRY_BRONZONG[];
extern const u8 DEX_ENTRY_BONSLY[];
extern const u8 DEX_ENTRY_MIME_JR[];
extern const u8 DEX_ENTRY_HAPPINY[];
extern const u8 DEX_ENTRY_CHATOT[];
extern const u8 DEX_ENTRY_SPIRITOMB[];
extern const u8 DEX_ENTRY_GIBLE[];
extern const u8 DEX_ENTRY_GABITE[];
extern const u8 DEX_ENTRY_GARCHOMP[];
extern const u8 DEX_ENTRY_MUNCHLAX[];
extern const u8 DEX_ENTRY_RIOLU[];
extern const u8 DEX_ENTRY_LUCARIO[];
extern const u8 DEX_ENTRY_HIPPOPOTAS[];
extern const u8 DEX_ENTRY_HIPPOWDON[];
extern const u8 DEX_ENTRY_SKORUPI[];
extern const u8 DEX_ENTRY_DRAPION[];
extern const u8 DEX_ENTRY_CROAGUNK[];
extern const u8 DEX_ENTRY_TOXICROAK[];
extern const u8 DEX_ENTRY_CARNIVINE[];
extern const u8 DEX_ENTRY_FINNEON[];
extern const u8 DEX_ENTRY_LUMINEON[];
extern const u8 DEX_ENTRY_MANTYKE[];
extern const u8 DEX_ENTRY_SNOVER[];
extern const u8 DEX_ENTRY_ABOMASNOW[];
extern const u8 DEX_ENTRY_WEAVILE[];
extern const u8 DEX_ENTRY_MAGNEZONE[];
extern const u8 DEX_ENTRY_LICKILICKY[];
extern const u8 DEX_ENTRY_RHYPERIOR[];
extern const u8 DEX_ENTRY_TANGROWTH[];
extern const u8 DEX_ENTRY_ELECTIVIRE[];
extern const u8 DEX_ENTRY_MAGMORTAR[];
extern const u8 DEX_ENTRY_TOGEKISS[];
extern const u8 DEX_ENTRY_YANMEGA[];
extern const u8 DEX_ENTRY_LEAFEON[];
extern const u8 DEX_ENTRY_GLACEON[];
extern const u8 DEX_ENTRY_GLISCOR[];
extern const u8 DEX_ENTRY_MAMOSWINE[];
extern const u8 DEX_ENTRY_PORYGON_Z[];
extern const u8 DEX_ENTRY_GALLADE[];
extern const u8 DEX_ENTRY_PROBOPASS[];
extern const u8 DEX_ENTRY_DUSKNOIR[];
extern const u8 DEX_ENTRY_FROSLASS[];
extern const u8 DEX_ENTRY_ROTOM[];
extern const u8 DEX_ENTRY_UXIE[];
extern const u8 DEX_ENTRY_MESPRIT[];
extern const u8 DEX_ENTRY_AZELF[];
extern const u8 DEX_ENTRY_DIALGA[];
extern const u8 DEX_ENTRY_PALKIA[];
extern const u8 DEX_ENTRY_HEATRAN[];
extern const u8 DEX_ENTRY_REGIGIGAS[];
extern const u8 DEX_ENTRY_GIRATINA[];
extern const u8 DEX_ENTRY_CRESSELIA[];
extern const u8 DEX_ENTRY_PHIONE[];
extern const u8 DEX_ENTRY_MANAPHY[];
extern const u8 DEX_ENTRY_DARKRAI[];
extern const u8 DEX_ENTRY_SHAYMIN[];
extern const u8 DEX_ENTRY_ARCEUS[];
extern const u8 DEX_ENTRY_VICTINI[];
extern const u8 DEX_ENTRY_SNIVY[];
extern const u8 DEX_ENTRY_SERVINE[];
extern const u8 DEX_ENTRY_SERPERIOR[];
extern const u8 DEX_ENTRY_TEPIG[];
extern const u8 DEX_ENTRY_PIGNITE[];
extern const u8 DEX_ENTRY_EMBOAR[];
extern const u8 DEX_ENTRY_OSHAWOTT[];
extern const u8 DEX_ENTRY_DEWOTT[];
extern const u8 DEX_ENTRY_SAMUROTT[];
extern const u8 DEX_ENTRY_PATRAT[];
extern const u8 DEX_ENTRY_WATCHOG[];
extern const u8 DEX_ENTRY_LILLIPUP[];
extern const u8 DEX_ENTRY_HERDIER[];
extern const u8 DEX_ENTRY_STOUTLAND[];
extern const u8 DEX_ENTRY_PURRLOIN[];
extern const u8 DEX_ENTRY_LIEPARD[];
extern const u8 DEX_ENTRY_PANSAGE[];
extern const u8 DEX_ENTRY_SIMISAGE[];
extern const u8 DEX_ENTRY_PANSEAR[];
extern const u8 DEX_ENTRY_SIMISEAR[];
extern const u8 DEX_ENTRY_PANPOUR[];
extern const u8 DEX_ENTRY_SIMIPOUR[];
extern const u8 DEX_ENTRY_MUNNA[];
extern const u8 DEX_ENTRY_MUSHARNA[];
extern const u8 DEX_ENTRY_PIDOVE[];
extern const u8 DEX_ENTRY_TRANQUILL[];
extern const u8 DEX_ENTRY_UNFEZANT[];
extern const u8 DEX_ENTRY_BLITZLE[];
extern const u8 DEX_ENTRY_ZEBSTRIKA[];
extern const u8 DEX_ENTRY_ROGGENROLA[];
extern const u8 DEX_ENTRY_BOLDORE[];
extern const u8 DEX_ENTRY_GIGALITH[];
extern const u8 DEX_ENTRY_WOOBAT[];
extern const u8 DEX_ENTRY_SWOOBAT[];
extern const u8 DEX_ENTRY_DRILBUR[];
extern const u8 DEX_ENTRY_EXCADRILL[];
extern const u8 DEX_ENTRY_AUDINO[];
extern const u8 DEX_ENTRY_TIMBURR[];
extern const u8 DEX_ENTRY_GURDURR[];
extern const u8 DEX_ENTRY_CONKELDURR[];
extern const u8 DEX_ENTRY_TYMPOLE[];
extern const u8 DEX_ENTRY_PALPITOAD[];
extern const u8 DEX_ENTRY_SEISMITOAD[];
extern const u8 DEX_ENTRY_THROH[];
extern const u8 DEX_ENTRY_SAWK[];
extern const u8 DEX_ENTRY_SEWADDLE[];
extern const u8 DEX_ENTRY_SWADLOON[];
extern const u8 DEX_ENTRY_LEAVANNY[];
extern const u8 DEX_ENTRY_VENIPEDE[];
extern const u8 DEX_ENTRY_WHIRLIPEDE[];
extern const u8 DEX_ENTRY_SCOLIPEDE[];
extern const u8 DEX_ENTRY_COTTONEE[];
extern const u8 DEX_ENTRY_WHIMSICOTT[];
extern const u8 DEX_ENTRY_PETILIL[];
extern const u8 DEX_ENTRY_LILLIGANT[];
extern const u8 DEX_ENTRY_BASCULIN[];
extern const u8 DEX_ENTRY_SANDILE[];
extern const u8 DEX_ENTRY_KROKOROK[];
extern const u8 DEX_ENTRY_KROOKODILE[];
extern const u8 DEX_ENTRY_DARUMAKA[];
extern const u8 DEX_ENTRY_DARMANITAN[];
extern const u8 DEX_ENTRY_MARACTUS[];
extern const u8 DEX_ENTRY_DWEBBLE[];
extern const u8 DEX_ENTRY_CRUSTLE[];
extern const u8 DEX_ENTRY_SCRAGGY[];
extern const u8 DEX_ENTRY_SCRAFTY[];
extern const u8 DEX_ENTRY_SIGILYPH[];
extern const u8 DEX_ENTRY_YAMASK[];
extern const u8 DEX_ENTRY_COFAGRIGUS[];
extern const u8 DEX_ENTRY_TIRTOUGA[];
extern const u8 DEX_ENTRY_CARRACOSTA[];
extern const u8 DEX_ENTRY_ARCHEN[];
extern const u8 DEX_ENTRY_ARCHEOPS[];
extern const u8 DEX_ENTRY_TRUBBISH[];
extern const u8 DEX_ENTRY_GARBODOR[];
extern const u8 DEX_ENTRY_ZORUA[];
extern const u8 DEX_ENTRY_ZOROARK[];
extern const u8 DEX_ENTRY_MINCCINO[];
extern const u8 DEX_ENTRY_CINCCINO[];
extern const u8 DEX_ENTRY_GOTHITA[];
extern const u8 DEX_ENTRY_GOTHORITA[];
extern const u8 DEX_ENTRY_GOTHITELLE[];
extern const u8 DEX_ENTRY_SOLOSIS[];
extern const u8 DEX_ENTRY_DUOSION[];
extern const u8 DEX_ENTRY_REUNICLUS[];
extern const u8 DEX_ENTRY_DUCKLETT[];
extern const u8 DEX_ENTRY_SWANNA[];
extern const u8 DEX_ENTRY_VANILLITE[];
extern const u8 DEX_ENTRY_VANILLISH[];
extern const u8 DEX_ENTRY_VANILLUXE[];
extern const u8 DEX_ENTRY_DEERLING[];
extern const u8 DEX_ENTRY_SAWSBUCK[];
extern const u8 DEX_ENTRY_EMOLGA[];
extern const u8 DEX_ENTRY_KARRABLAST[];
extern const u8 DEX_ENTRY_ESCAVALIER[];
extern const u8 DEX_ENTRY_FOONGUS[];
extern const u8 DEX_ENTRY_AMOONGUSS[];
extern const u8 DEX_ENTRY_FRILLISH[];
extern const u8 DEX_ENTRY_JELLICENT[];
extern const u8 DEX_ENTRY_ALOMOMOLA[];
extern const u8 DEX_ENTRY_JOLTIK[];
extern const u8 DEX_ENTRY_GALVANTULA[];
extern const u8 DEX_ENTRY_FERROSEED[];
extern const u8 DEX_ENTRY_FERROTHORN[];
extern const u8 DEX_ENTRY_KLINK[];
extern const u8 DEX_ENTRY_KLANG[];
extern const u8 DEX_ENTRY_KLINKLANG[];
extern const u8 DEX_ENTRY_TYNAMO[];
extern const u8 DEX_ENTRY_EELEKTRIK[];
extern const u8 DEX_ENTRY_EELEKTROSS[];
extern const u8 DEX_ENTRY_ELGYEM[];
extern const u8 DEX_ENTRY_BEHEEYEM[];
extern const u8 DEX_ENTRY_LITWICK[];
extern const u8 DEX_ENTRY_LAMPENT[];
extern const u8 DEX_ENTRY_CHANDELURE[];
extern const u8 DEX_ENTRY_AXEW[];
extern const u8 DEX_ENTRY_FRAXURE[];
extern const u8 DEX_ENTRY_HAXORUS[];
extern const u8 DEX_ENTRY_CUBCHOO[];
extern const u8 DEX_ENTRY_BEARTIC[];
extern const u8 DEX_ENTRY_CRYOGONAL[];
extern const u8 DEX_ENTRY_SHELMET[];
extern const u8 DEX_ENTRY_ACCELGOR[];
extern const u8 DEX_ENTRY_STUNFISK[];
extern const u8 DEX_ENTRY_MIENFOO[];
extern const u8 DEX_ENTRY_MIENSHAO[];
extern const u8 DEX_ENTRY_DRUDDIGON[];
extern const u8 DEX_ENTRY_GOLETT[];
extern const u8 DEX_ENTRY_GOLURK[];
extern const u8 DEX_ENTRY_PAWNIARD[];
extern const u8 DEX_ENTRY_BISHARP[];
extern const u8 DEX_ENTRY_BOUFFALANT[];
extern const u8 DEX_ENTRY_RUFFLET[];
extern const u8 DEX_ENTRY_BRAVIARY[];
extern const u8 DEX_ENTRY_VULLABY[];
extern const u8 DEX_ENTRY_MANDIBUZZ[];
extern const u8 DEX_ENTRY_HEATMOR[];
extern const u8 DEX_ENTRY_DURANT[];
extern const u8 DEX_ENTRY_DEINO[];
extern const u8 DEX_ENTRY_ZWEILOUS[];
extern const u8 DEX_ENTRY_HYDREIGON[];
extern const u8 DEX_ENTRY_LARVESTA[];
extern const u8 DEX_ENTRY_VOLCARONA[];
extern const u8 DEX_ENTRY_COBALION[];
extern const u8 DEX_ENTRY_TERRAKION[];
extern const u8 DEX_ENTRY_VIRIZION[];
extern const u8 DEX_ENTRY_TORNADUS[];
extern const u8 DEX_ENTRY_THUNDURUS[];
extern const u8 DEX_ENTRY_RESHIRAM[];
extern const u8 DEX_ENTRY_ZEKROM[];
extern const u8 DEX_ENTRY_LANDORUS[];
extern const u8 DEX_ENTRY_KYUREM[];
extern const u8 DEX_ENTRY_KELDEO[];
extern const u8 DEX_ENTRY_MELOETTA[];
extern const u8 DEX_ENTRY_GENESECT[];
extern const u8 DEX_ENTRY_CHESPIN[];
extern const u8 DEX_ENTRY_QUILLADIN[];
extern const u8 DEX_ENTRY_CHESNAUGHT[];
extern const u8 DEX_ENTRY_FENNEKIN[];
extern const u8 DEX_ENTRY_BRAIXEN[];
extern const u8 DEX_ENTRY_DELPHOX[];
extern const u8 DEX_ENTRY_FROAKIE[];
extern const u8 DEX_ENTRY_FROGADIER[];
extern const u8 DEX_ENTRY_GRENINJA[];
extern const u8 DEX_ENTRY_BUNNELBY[];
extern const u8 DEX_ENTRY_DIGGERSBY[];
extern const u8 DEX_ENTRY_FLETCHLING[];
extern const u8 DEX_ENTRY_FLETCHINDER[];
extern const u8 DEX_ENTRY_TALONFLAME[];
extern const u8 DEX_ENTRY_SCATTERBUG[];
extern const u8 DEX_ENTRY_SPEWPA[];
extern const u8 DEX_ENTRY_VIVILLON[];
extern const u8 DEX_ENTRY_LITLEO[];
extern const u8 DEX_ENTRY_PYROAR[];
extern const u8 DEX_ENTRY_FLABEBE[];
extern const u8 DEX_ENTRY_FLOETTE[];
extern const u8 DEX_ENTRY_FLORGES[];
extern const u8 DEX_ENTRY_SKIDDO[];
extern const u8 DEX_ENTRY_GOGOAT[];
extern const u8 DEX_ENTRY_PANCHAM[];
extern const u8 DEX_ENTRY_PANGORO[];
extern const u8 DEX_ENTRY_FURFROU[];
extern const u8 DEX_ENTRY_ESPURR[];
extern const u8 DEX_ENTRY_MEOWSTIC[];
extern const u8 DEX_ENTRY_HONEDGE[];
extern const u8 DEX_ENTRY_DOUBLADE[];
extern const u8 DEX_ENTRY_AEGISLASH[];
extern const u8 DEX_ENTRY_SPRITZEE[];
extern const u8 DEX_ENTRY_AROMATISSE[];
extern const u8 DEX_ENTRY_SWIRLIX[];
extern const u8 DEX_ENTRY_SLURPUFF[];
extern const u8 DEX_ENTRY_INKAY[];
extern const u8 DEX_ENTRY_MALAMAR[];
extern const u8 DEX_ENTRY_BINACLE[];
extern const u8 DEX_ENTRY_BARBARACLE[];
extern const u8 DEX_ENTRY_SKRELP[];
extern const u8 DEX_ENTRY_DRAGALGE[];
extern const u8 DEX_ENTRY_CLAUNCHER[];
extern const u8 DEX_ENTRY_CLAWITZER[];
extern const u8 DEX_ENTRY_HELIOPTILE[];
extern const u8 DEX_ENTRY_HELIOLISK[];
extern const u8 DEX_ENTRY_TYRUNT[];
extern const u8 DEX_ENTRY_TYRANTRUM[];
extern const u8 DEX_ENTRY_AMAURA[];
extern const u8 DEX_ENTRY_AURORUS[];
extern const u8 DEX_ENTRY_SYLVEON[];
extern const u8 DEX_ENTRY_HAWLUCHA[];
extern const u8 DEX_ENTRY_DEDENNE[];
extern const u8 DEX_ENTRY_CARBINK[];
extern const u8 DEX_ENTRY_GOOMY[];
extern const u8 DEX_ENTRY_SLIGGOO[];
extern const u8 DEX_ENTRY_GOODRA[];
extern const u8 DEX_ENTRY_KLEFKI[];
extern const u8 DEX_ENTRY_PHANTUMP[];
extern const u8 DEX_ENTRY_TREVENANT[];
extern const u8 DEX_ENTRY_PUMPKABOO[];
extern const u8 DEX_ENTRY_GOURGEIST[];
extern const u8 DEX_ENTRY_BERGMITE[];
extern const u8 DEX_ENTRY_AVALUGG[];
extern const u8 DEX_ENTRY_NOIBAT[];
extern const u8 DEX_ENTRY_NOIVERN[];
extern const u8 DEX_ENTRY_XERNEAS[];
extern const u8 DEX_ENTRY_YVELTAL[];
extern const u8 DEX_ENTRY_ZYGARDE[];
extern const u8 DEX_ENTRY_DIANCIE[];
extern const u8 DEX_ENTRY_HOOPA[];
extern const u8 DEX_ENTRY_VOLCANION[];
extern const u8 DEX_ENTRY_ROWLET[];
extern const u8 DEX_ENTRY_DARTRIX[];
extern const u8 DEX_ENTRY_DECIDUEYE[];
extern const u8 DEX_ENTRY_LITTEN[];
extern const u8 DEX_ENTRY_TORRACAT[];
extern const u8 DEX_ENTRY_INCINEROAR[];
extern const u8 DEX_ENTRY_POPPLIO[];
extern const u8 DEX_ENTRY_BRIONNE[];
extern const u8 DEX_ENTRY_PRIMARINA[];
extern const u8 DEX_ENTRY_PIKIPEK[];
extern const u8 DEX_ENTRY_TRUMBEAK[];
extern const u8 DEX_ENTRY_TOUCANNON[];
extern const u8 DEX_ENTRY_YUNGOOS[];
extern const u8 DEX_ENTRY_GUMSHOOS[];
extern const u8 DEX_ENTRY_GRUBBIN[];
extern const u8 DEX_ENTRY_CHARJABUG[];
extern const u8 DEX_ENTRY_VIKAVOLT[];
extern const u8 DEX_ENTRY_CRABRAWLER[];
extern const u8 DEX_ENTRY_CRABOMINABLE[];
extern const u8 DEX_ENTRY_ORICORIO[];
extern const u8 DEX_ENTRY_CUTIEFLY[];
extern const u8 DEX_ENTRY_RIBOMBEE[];
extern const u8 DEX_ENTRY_ROCKRUFF[];
extern const u8 DEX_ENTRY_LYCANROC[];
extern const u8 DEX_ENTRY_WISHIWASHI[];
extern const u8 DEX_ENTRY_MAREANIE[];
extern const u8 DEX_ENTRY_TOXAPEX[];
extern const u8 DEX_ENTRY_MUDBRAY[];
extern const u8 DEX_ENTRY_MUDSDALE[];
extern const u8 DEX_ENTRY_DEWPIDER[];
extern const u8 DEX_ENTRY_ARAQUANID[];
extern const u8 DEX_ENTRY_FOMANTIS[];
extern const u8 DEX_ENTRY_LURANTIS[];
extern const u8 DEX_ENTRY_MORELULL[];
extern const u8 DEX_ENTRY_SHIINOTIC[];
extern const u8 DEX_ENTRY_SALANDIT[];
extern const u8 DEX_ENTRY_SALAZZLE[];
extern const u8 DEX_ENTRY_STUFFUL[];
extern const u8 DEX_ENTRY_BEWEAR[];
extern const u8 DEX_ENTRY_BOUNSWEET[];
extern const u8 DEX_ENTRY_STEENEE[];
extern const u8 DEX_ENTRY_TSAREENA[];
extern const u8 DEX_ENTRY_COMFEY[];
extern const u8 DEX_ENTRY_ORANGURU[];
extern const u8 DEX_ENTRY_PASSIMIAN[];
extern const u8 DEX_ENTRY_WIMPOD[];
extern const u8 DEX_ENTRY_GOLISOPOD[];
extern const u8 DEX_ENTRY_SANDYGAST[];
extern const u8 DEX_ENTRY_PALOSSAND[];
extern const u8 DEX_ENTRY_PYUKUMUKU[];
extern const u8 DEX_ENTRY_TYPE_NULL[];
extern const u8 DEX_ENTRY_SILVALLY[];
extern const u8 DEX_ENTRY_MINIOR[];
extern const u8 DEX_ENTRY_KOMALA[];
extern const u8 DEX_ENTRY_TURTONATOR[];
extern const u8 DEX_ENTRY_TOGEDEMARU[];
extern const u8 DEX_ENTRY_MIMIKYU[];
extern const u8 DEX_ENTRY_BRUXISH[];
extern const u8 DEX_ENTRY_DRAMPA[];
extern const u8 DEX_ENTRY_DHELMISE[];
extern const u8 DEX_ENTRY_JANGMO_O[];
extern const u8 DEX_ENTRY_HAKAMO_O[];
extern const u8 DEX_ENTRY_KOMMO_O[];
extern const u8 DEX_ENTRY_TAPU_KOKO[];
extern const u8 DEX_ENTRY_TAPU_LELE[];
extern const u8 DEX_ENTRY_TAPU_BULU[];
extern const u8 DEX_ENTRY_TAPU_FINI[];
extern const u8 DEX_ENTRY_COSMOG[];
extern const u8 DEX_ENTRY_COSMOEM[];
extern const u8 DEX_ENTRY_SOLGALEO[];
extern const u8 DEX_ENTRY_LUNALA[];
extern const u8 DEX_ENTRY_NIHILEGO[];
extern const u8 DEX_ENTRY_BUZZWOLE[];
extern const u8 DEX_ENTRY_PHEROMOSA[];
extern const u8 DEX_ENTRY_XURKITREE[];
extern const u8 DEX_ENTRY_CELESTEELA[];
extern const u8 DEX_ENTRY_KARTANA[];
extern const u8 DEX_ENTRY_GUZZLORD[];
extern const u8 DEX_ENTRY_NECROZMA[];
extern const u8 DEX_ENTRY_MAGEARNA[];
extern const u8 DEX_ENTRY_MARSHADOW[];
extern const u8 DEX_ENTRY_POIPOLE[];
extern const u8 DEX_ENTRY_NAGANADEL[];
extern const u8 DEX_ENTRY_STAKATAKA[];
extern const u8 DEX_ENTRY_BLACEPHALON[];
extern const u8 DEX_ENTRY_ZERAORA[];
extern const u8 DEX_ENTRY_MELTAN[];
extern const u8 DEX_ENTRY_MELMETAL[];
extern const u8 DEX_ENTRY_GROOKEY[];
extern const u8 DEX_ENTRY_THWACKEY[];
extern const u8 DEX_ENTRY_RILLABOOM[];
extern const u8 DEX_ENTRY_SCORBUNNY[];
extern const u8 DEX_ENTRY_RABOOT[];
extern const u8 DEX_ENTRY_CINDERACE[];
extern const u8 DEX_ENTRY_SOBBLE[];
extern const u8 DEX_ENTRY_DRIZZILE[];
extern const u8 DEX_ENTRY_INTELEON[];
extern const u8 DEX_ENTRY_SKWOVET[];
extern const u8 DEX_ENTRY_GREEDENT[];
extern const u8 DEX_ENTRY_ROOKIDEE[];
extern const u8 DEX_ENTRY_CORVISQUIRE[];
extern const u8 DEX_ENTRY_CORVIKNIGHT[];
extern const u8 DEX_ENTRY_BLIPBUG[];
extern const u8 DEX_ENTRY_DOTTLER[];
extern const u8 DEX_ENTRY_ORBEETLE[];
extern const u8 DEX_ENTRY_NICKIT[];
extern const u8 DEX_ENTRY_THIEVUL[];
extern const u8 DEX_ENTRY_GOSSIFLEUR[];
extern const u8 DEX_ENTRY_ELDEGOSS[];
extern const u8 DEX_ENTRY_WOOLOO[];
extern const u8 DEX_ENTRY_DUBWOOL[];
extern const u8 DEX_ENTRY_CHEWTLE[];
extern const u8 DEX_ENTRY_DREDNAW[];
extern const u8 DEX_ENTRY_YAMPER[];
extern const u8 DEX_ENTRY_BOLTUND[];
extern const u8 DEX_ENTRY_ROLYCOLY[];
extern const u8 DEX_ENTRY_CARKOL[];
extern const u8 DEX_ENTRY_COALOSSAL[];
extern const u8 DEX_ENTRY_APPLIN[];
extern const u8 DEX_ENTRY_FLAPPLE[];
extern const u8 DEX_ENTRY_APPLETUN[];
extern const u8 DEX_ENTRY_SILICOBRA[];
extern const u8 DEX_ENTRY_SANDACONDA[];
extern const u8 DEX_ENTRY_CRAMORANT[];
extern const u8 DEX_ENTRY_ARROKUDA[];
extern const u8 DEX_ENTRY_BARRASKEWDA[];
extern const u8 DEX_ENTRY_TOXEL[];
extern const u8 DEX_ENTRY_TOXTRICITY[];
extern const u8 DEX_ENTRY_SIZZLIPEDE[];
extern const u8 DEX_ENTRY_CENTISKORCH[];
extern const u8 DEX_ENTRY_CLOBBOPUS[];
extern const u8 DEX_ENTRY_GRAPPLOCT[];
extern const u8 DEX_ENTRY_SINISTEA[];
extern const u8 DEX_ENTRY_POLTEAGEIST[];
extern const u8 DEX_ENTRY_HATENNA[];
extern const u8 DEX_ENTRY_HATTREM[];
extern const u8 DEX_ENTRY_HATTERENE[];
extern const u8 DEX_ENTRY_IMPIDIMP[];
extern const u8 DEX_ENTRY_MORGREM[];
extern const u8 DEX_ENTRY_GRIMMSNARL[];
extern const u8 DEX_ENTRY_OBSTAGOON[];
extern const u8 DEX_ENTRY_PERRSERKER[];
extern const u8 DEX_ENTRY_CURSOLA[];
extern const u8 DEX_ENTRY_SIRFETCHD[];
extern const u8 DEX_ENTRY_MR_RIME[];
extern const u8 DEX_ENTRY_RUNERIGUS[];
extern const u8 DEX_ENTRY_MILCERY[];
extern const u8 DEX_ENTRY_ALCREMIE_STRAWBERRY[];
extern const u8 DEX_ENTRY_FALINKS[];
extern const u8 DEX_ENTRY_PINCURCHIN[];
extern const u8 DEX_ENTRY_SNOM[];
extern const u8 DEX_ENTRY_FROSMOTH[];
extern const u8 DEX_ENTRY_STONJOURNER[];
extern const u8 DEX_ENTRY_EISCUE[];
extern const u8 DEX_ENTRY_INDEEDEE[];
extern const u8 DEX_ENTRY_MORPEKO[];
extern const u8 DEX_ENTRY_CUFANT[];
extern const u8 DEX_ENTRY_COPPERAJAH[];
extern const u8 DEX_ENTRY_DRACOZOLT[];
extern const u8 DEX_ENTRY_ARCTOZOLT[];
extern const u8 DEX_ENTRY_DRACOVISH[];
extern const u8 DEX_ENTRY_ARCTOVISH[];
extern const u8 DEX_ENTRY_DURALUDON[];
extern const u8 DEX_ENTRY_DREEPY[];
extern const u8 DEX_ENTRY_DRAKLOAK[];
extern const u8 DEX_ENTRY_DRAGAPULT[];
extern const u8 DEX_ENTRY_ZACIAN[];
extern const u8 DEX_ENTRY_ZAMAZENTA[];
extern const u8 DEX_ENTRY_ETERNATUS[];
extern const u8 DEX_ENTRY_KUBFU[];
extern const u8 DEX_ENTRY_URSHIFU_SINGLE[];
extern const u8 DEX_ENTRY_ZARUDE[];
extern const u8 DEX_ENTRY_REGIELEKI[];
extern const u8 DEX_ENTRY_REGIDRAGO[];
extern const u8 DEX_ENTRY_GLASTRIER[];
extern const u8 DEX_ENTRY_SPECTRIER[];
extern const u8 DEX_ENTRY_CALYREX[];

extern const u8 DEX_ENTRY_RATTATA_A[];
extern const u8 DEX_ENTRY_RATICATE_A[];
extern const u8 DEX_ENTRY_RAICHU_A[];
extern const u8 DEX_ENTRY_SANDSHREW_A[];
extern const u8 DEX_ENTRY_SANDSLASH_A[];
extern const u8 DEX_ENTRY_VULPIX_A[];
extern const u8 DEX_ENTRY_NINETALES_A[];
extern const u8 DEX_ENTRY_DIGLETT_A[];
extern const u8 DEX_ENTRY_DUGTRIO_A[];
extern const u8 DEX_ENTRY_MEOWTH_A[];
extern const u8 DEX_ENTRY_MEOWTH_G[];
extern const u8 DEX_ENTRY_PERSIAN_A[];
extern const u8 DEX_ENTRY_GEODUDE_A[];
extern const u8 DEX_ENTRY_GRAVELER_A[];
extern const u8 DEX_ENTRY_GOLEM_A[];
extern const u8 DEX_ENTRY_PONYTA_G[];
extern const u8 DEX_ENTRY_RAPIDASH_G[];
extern const u8 DEX_ENTRY_SLOWPOKE_G[];
extern const u8 DEX_ENTRY_SLOWBRO_G[];
extern const u8 DEX_ENTRY_FARFETCHD_G[];
extern const u8 DEX_ENTRY_GRIMER_A[];
extern const u8 DEX_ENTRY_MUK_A[];
extern const u8 DEX_ENTRY_EXEGGUTOR_A[];
extern const u8 DEX_ENTRY_MAROWAK_A[];
extern const u8 DEX_ENTRY_WEEZING_G[];
extern const u8 DEX_ENTRY_MR_MIME_G[];
extern const u8 DEX_ENTRY_ARTICUNO_G[];
extern const u8 DEX_ENTRY_ZAPDOS_G[];
extern const u8 DEX_ENTRY_MOLTRES_G[];
extern const u8 DEX_ENTRY_SLOWKING_G[];
extern const u8 DEX_ENTRY_CORSOLA_G[];
extern const u8 DEX_ENTRY_ZIGZAGOON_G[];
extern const u8 DEX_ENTRY_LINOONE_G[];
extern const u8 DEX_ENTRY_DARUMAKA_G[];
extern const u8 DEX_ENTRY_DARMANITAN_G[];
extern const u8 DEX_ENTRY_DARMANITAN_G_ZEN[];
extern const u8 DEX_ENTRY_YAMASK_G[];
extern const u8 DEX_ENTRY_STUNFISK_G[];
extern const u8 DEX_ENTRY_ZYGARDE_10[];
extern const u8 DEX_ENTRY_ZYGARDE_COMPLETE[];
extern const u8 DEX_ENTRY_ORICORIO_Y[];
extern const u8 DEX_ENTRY_ORICORIO_P[];
extern const u8 DEX_ENTRY_ORICORIO_S[];
extern const u8 DEX_ENTRY_LYCANROC_N[];
extern const u8 DEX_ENTRY_LYCANROC_DUSK[];
extern const u8 DEX_ENTRY_WISHIWASHI_S[];
extern const u8 DEX_ENTRY_NECROZMA_DUSK_MANE[];
extern const u8 DEX_ENTRY_NECROZMA_DAWN_WINGS[];
extern const u8 DEX_ENTRY_NECROZMA_ULTRA[];
extern const u8 DEX_ENTRY_CRAMORANT_GULPING[];
extern const u8 DEX_ENTRY_CRAMORANT_GORGING[];
extern const u8 DEX_ENTRY_TOXTRICITY_LOW_KEY[];
extern const u8 DEX_ENTRY_SINISTEA_CHIPPED[];
extern const u8 DEX_ENTRY_POLTEAGEIST_CHIPPED[];
extern const u8 DEX_ENTRY_ALCREMIE_BERRY[];
extern const u8 DEX_ENTRY_ALCREMIE_CLOVER[];
extern const u8 DEX_ENTRY_ALCREMIE_FLOWER[];
extern const u8 DEX_ENTRY_ALCREMIE_LOVE[];
extern const u8 DEX_ENTRY_ALCREMIE_RIBBON[];
extern const u8 DEX_ENTRY_ALCREMIE_STAR[];
extern const u8 DEX_ENTRY_EISCUE_NOICE[];
extern const u8 DEX_ENTRY_INDEEDEE_FEMALE[];
extern const u8 DEX_ENTRY_MORPEKO_HANGRY[];
extern const u8 DEX_ENTRY_ZACIAN_CROWNED[];
extern const u8 DEX_ENTRY_ZAMAZENTA_CROWNED[];
extern const u8 DEX_ENTRY_ETERNATUS_ETERNAMAX[];
extern const u8 DEX_ENTRY_URSHIFU_RAPID[];
extern const u8 DEX_ENTRY_ZARUDE_DADA[];
extern const u8 DEX_ENTRY_CALYREX_ICE_RIDER[];
extern const u8 DEX_ENTRY_CALYREX_SHADOW_RIDER[];
